In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"practDatasets/dirty_cafe_sales.csv")

In [3]:
df = df.drop_duplicates()

In [224]:
df.head(60)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,0.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
6,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
7,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
8,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
9,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
10,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
11,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
12,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
13,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
14,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
15,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
16,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
17,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
18,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
19,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
20,TXN_9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28
21,TXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
22,TXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
23,TXN_6342161,Salad,5,5.0,25.0,ERROR,Takeaway,2023-01-08
24,TXN_8614868,Smoothie,5,4.0,20.0,Digital Wallet,Takeaway,2023-12-05
25,TXN_6421134,Sandwich,4,4.0,16.0,Cash,Takeaway,2023-11-03
26,TXN_3068204,Cookie,1,1.0,1.0,Credit Card,Takeaway,2023-10-03
27,TXN_8471743,Error,5,3.0,15.0,Digital Wallet,In-store,2023-04-06
28,TXN_2621580,Tea,2,1.5,3.0,Cash,In-store,2023-03-22
29,TXN_4726376,Cake,2,3.0,6.0,Credit Card,In-store,2023-01-31
30,TXN_1900620,Smoothie,2,4.0,8.0,Credit Card,ERROR,2023-12-14
31,TXN_6420335,Coffee,1,2.0,2.0,Cash,Takeaway,2023-07-16
32,TXN_3829165,Juice,4,3.0,12.0,Cash,In-store,2023-06-15
33,TXN_3748616,Coffee,2,2.0,4.0,Credit Card,In-store,2023-12-09
34,TXN_5266394,Cake,3,3.0,9.0,Cash,In-store,2023-10-28
35,TXN_8718498,Cake,5,3.0,15.0,Credit Card,ERROR,2023-04-30
36,TXN_9487821,Error,1,5.0,5.0,Digital Wallet,Takeaway,2023-05-24
37,TXN_8976658,Tea,2,1.5,3.0,Credit Card,In-store,2023-08-16
38,TXN_6289610,Juice,3,3.0,0.0,Cash,Takeaway,2023-08-07
39,TXN_8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20
40,TXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10
41,TXN_3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15
42,TXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27
43,TXN_8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25
44,TXN_3808639,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-12-15
45,TXN_6955416,Salad,4,5.0,20.0,ERROR,In-store,2023-02-25
46,TXN_3775339,Cookie,3,1.0,3.0,Credit Card,UNKNOWN,2023-04-03
47,TXN_4358673,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-12-28
48,TXN_1001832,Salad,2,5.0,10.0,Cash,Takeaway,UNKNOWN
49,TXN_4368416,Salad,2,5.0,10.0,Credit Card,Takeaway,2023-02-24
50,TXN_6258471,Coffee,5,2.0,10.0,Digital Wallet,In-store,2023-09-23
51,TXN_4685453,Tea,4,1.5,6.0,Cash,In-store,2023-09-14
52,TXN_9096052,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-12-28
53,TXN_5916991,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-02-06
54,TXN_3407169,Sandwich,2,4.0,8.0,Cash,In-store,2023-03-11
55,TXN_2181545,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-07-14
56,TXN_1150033,Juice,5,3.0,15.0,Cash,In-store,2023-04-18
57,TXN_8700451,Tea,5,1.5,7.5,Credit Card,Takeaway,2023-12-12
58,TXN_6380550,Coffee,5,2.0,10.0,Cash,In-store,2023-01-05
59,TXN_4885518,Salad,3,5.0,15.0,Credit Card,In-store,2023-06-10

In [5]:
# df["Transaction ID"].str.contains("TXN").count() 
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [6]:
df.dropna(subset=["Item","Payment Method","Location"],inplace =True)

In [7]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03

In [8]:
for x in df.index:
    str(df.loc[x,"Item"])

In [9]:

        
df = df[df["Item"] != "UNKNOWN"]

In [10]:
df[df["Item"] == "UNKNOWN"].count()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [17]:
# df.reset_index(inplace =True)
# df.drop(columns = ["index","level_0"],inplace =True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
4661,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
4662,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
4663,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
4664,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
4665,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [24]:
# df.dropna(inplace =True)
# for x in df.index:
#     str(df.loc[x,"Quantity"])

# df = df[df["Quantity"]!="UNKNOWN"]  

# df = df[df["Quantity"]!="ERROR"]  


# for x in df.index:
#     print(df.loc[x,"Quantity"])

# df = df[df["Quantity"] != 0]

In [25]:
for x in df.index:
     df.loc[x,"Item"] = df.loc[x,"Item"][0].upper() + df.loc[x,"Item"][1:].lower()

In [26]:
for x in df.index:
    print(df.loc[x,"Quantity"])

2
4
4
2
2
4
5
2
2
3
2
5
4
4
3
5
5
4
4
2
1
2
4
5
5
4
1
5
2
2
2
1
4
2
3
5
1
2
3
3
5
4
4
4
2
4
3
5
2
2
5
4
4
2
2
4
5
5
5
3
5
4
2
3
5
1
1
3
3
4
3
3
5
3
2
3
5
4
4
3
2
2
3
1
1
3
4
1
4
3
1
1
5
1
1
4
4
1
1
2
3
3
2
2
3
4
1
2
5
2
5
1
5
1
4
4
5
5
5
1
4
5
1
3
3
1
3
2
3
3
3
4
3
4
5
5
3
2
3
1
3
5
2
5
2
3
5
3
4
3
4
4
2
3
4
2
3
1
2
1
1
5
5
3
5
1
5
4
1
4
1
5
3
4
1
4
2
4
3
1
4
5
1
3
2
5
5
2
4
2
3
5
1
1
5
4
3
4
4
2
4
1
4
4
4
1
1
4
5
5
1
4
3
4
1
4
3
2
2
1
3
2
3
3
3
3
2
4
1
5
4
3
1
3
5
5
4
5
4
3
3
5
5
1
5
3
5
2
5
1
1
1
1
1
4
2
3
3
5
5
4
2
5
2
5
5
1
2
4
1
4
1
5
3
5
2
1
3
1
3
5
1
2
5
3
5
2
4
1
1
3
4
3
1
4
5
3
5
5
1
1
2
2
3
5
4
4
4
3
1
3
2
3
3
4
1
1
5
1
4
5
5
3
3
2
3
5
1
5
1
4
3
2
3
4
5
1
3
3
5
3
4
4
4
5
4
2
1
1
3
3
3
3
4
2
3
4
1
3
3
5
3
4
4
4
3
1
3
2
1
4
4
4
4
3
3
1
4
3
2
1
5
2
3
5
5
3
5
5
2
5
2
3
3
1
1
2
5
1
5
2
1
1
3
4
1
2
2
2
5
5
5
5
1
2
5
1
1
1
4
5
5
2
4
1
4
2
3
2
5
4
1
1
3
4
1
1
4
2
2
3
2
4
3
2
2
1
3
1
3
2
3
1
5
4
5
1
5
3
2
2
1
2
2
2
1
5
3
5
1
1
2
4
5
4
5
2
3
2
2
5
4
2
3
3
3
5
3
3
5
2
1
5
2
1
2
1
2
4
5
1
2
1
1
2
5
2
4
5
2
2
5
5
4
4
4
5
4
4
2
3
2
1
5
5
4
2
2
4
1
4
5
2
2
2
4
3
1
2
5
4
5
1
4
1
5
1
3
1
2
1
1
2
2
4
5
4
1
3
4
1
2
5
3
2
4
3
5
5
1
3
4
2
1
2
2
3
5
4
5
5
5
3
3
3
3
1
4
4
1
3
3
3
2
5
1
2
5
2
5
1
1
2
5
4
1
4
2
4
1
2
5
4
4
1
3
5
2
2
4
5
3
3
5
1
4
5
2
2
4
4
4
5
1
4
4
5
5
2
2
2
1
1
1
2
5
5
5
5
4
4
1
1
4
5
1
1
3
2
1
4
5
2
1
4
4
3
5
4
1
2
4
2
2
1
3
2
1
3
3
1
3
5
2
2
1
4
3
1
3
5
4
3
2
2
2
5
4
4
3
5
4
2
2
4
2
1
2
5
5
5
2
2
5
4
5
5
1
1
1
3
1
5
2
1
2
3
2
5
4
5
5
5
4
2
1
4
5
2
2
5
5
5
2
5
1
5
1
1
2
5
1
1
1
5
1
2
1
2
5
2
4
1
1
5
5
1
4
2
5
5
3
5
1
3
1
5
5
5
2
2
5
5
3
5
4
5
3
2
1
2
5
2
2
2
2
1
5
4
5
5
3
1
5
4
1
2
3
5
3
5
5
3
2
5
5
4
4
3
2
4
4
3
5
5
4
5
5
1
5
3
4
3
5
2
2
1
5
3
1
1
5
5
5
3
1
2
3
2
3
3
3
4
2
2
3
1
5
2
5
1
2
3
5
4
1
2
3
5
1
3
3
3
5
4
3
4
4
2
5
3
1
1
4
4
2
4
3
4
3
1
2
1
5
5
1
3
3
3
3
4
3
3
3
1
3
4
4
1
3
2
2
4
1
4
1
5
4
3
5
1
4
2
1
1
2
2
1
1
4
2
2
3
3
5
3
5
3
2
2
2
2
3
2
2
5
3
1
3
4
4
5
3
5
3
2
5
1
5
4
3
4
4
1
2
4
4
5
5
5
3
2
2
3
3
3
2
5
3
1
5
5
3
5
4
2
2
1
2
3
5
3
3
2
4
4
1
4
3
5
3
1
5
2
4
2
1
2
4
1
3
4
4
2
1
3
1
5
1
2
5
1
3
5
5
4
5
2
2
3
5
1
3
1
1
5
2
2
5
3
4
5
5
4
1
3
1
4
4
1
4
4
5
3
1
5
1
5
2
5
4
5
3
1
5
4
4
1
4
1
4
5
4
2
1
3
4
1
4
1
4
5
3
2
2
1
3
2
5
4
5
5
5
2
4
4
4
5
2
4
3
4
4
2
5
3
2
2
1
2
4
2
5
5
4
2
3
4
4
1
2
4
4
3
5
2
5
5
3
1
4
1
5
2
5
3
3
5
5
4
4
3
2
1
2
5
1
2
5
2
1
2
1
4
1
1
1
5
2
1
1
1
4
1
2
3
5
2
3
4
1
4
5
3
3
5
4
4
1
2
1
3
2
2
1
3
5
3
5
2
1
5
5
4
2
5
3
2
1
5
1
5
2
3
5
3
4
5
3
3
2
3
2
5
5
2
4
3
2
5
2
3
1
3
1
1
2
1
4
5
5
3
3
5
2
4
4
3
3
4
2
5
3
3
1
5
4
5
4
4
3
1
1
2
5
4
2
2
5
3
2
2
5
4
4
5
1
4
5
2
3
3
4
4
1
2
5
4
1
5
1
3
3
5
5
4
5
3
1
4
5
2
2
3
1
4
3
5
3
3
3
2
1
2
3
1
2
5
5
5
1
5
2
5
2
3
4
2
1
2
1
2
2
2
4
2
4
4
1
1
5
2
3
3
3
4
3
2
3
5
4
4
5
1
1
5
5
3
3
3
1
2
3
1
4
4
5
2
3
3
3
4
5
4
5
1
2
3
2
1
2
3
1
4
5
5
2
4
3
3
3
2
5
5
2
2
5
1
3
1
2
2
5
4
3
5
2
3
3
4
4
1
5
5
3
4
5
2
1
4
1
4
5
5
4
3
1
5
5
2
4
3
5
4
4
3
1
5
3
3
5
4
5
1
3
1
2
5
2
5
1
5
4
2
3
5
1
4
3
4
1
4
3
1
3
3
3
3
1
3
5
1
4
5
4
2
1
4
1
1
2
2
2
4
3
1
1
1
4
2
4
2
5
3
2
4
1
3
5
4
1
3
5
4
3
5
5
3
1
1
5
3
5
1
5
1
2
1
5
5
5
3
5
5
5
5
4
5
2
4
4
4
1
3
1
4
1
5
2
3
1
5
4
1
4
2
2
1
5
2
4
3
3
2
3
5
2
1
4
2
5
4
4
3
1
4
4
1
4
2
1
5
2
3
2
2
3
5
5
5
3
4
4
2
5
2
3
2
3
4
2
1
4
4
3
4
2
5
2
2
3
1
4
2
1
4
1
2
1
1
5
4
4
4
3
3
3
3
1
2
5
3
3
2
1
1
4
1
5
3
2
4
4
2
3
5
4
3
5
5
3
2
2
5
4
4
1
4
2
1
3
2
2
1
2
4
1
5
2
5
3
5
4
1
2
4
5
1
5
2
3
4
2
4
1
1
1
3
1
3
5
4
5
4
4
1
3
4
4
3
5
4
4
2
1
3
3
1
5
2
2
2
3
5
2
4
4
5
5
3
5
1
4
3
5
4
1
1
2
2
2
4
4
4
5
5
3
3
4
4
3
1
5
1
4
2
5
1
5
1
4
3
2
2
5
5
5
1
3
1
1
2
2
5
2
4
5
2
5
2
5
4
1
3
2
1
5
4
3
1
2
2
1
4
1
4
1
4
2
1
4
5
3
1
4
1
4
3
5
5
2
1
2
3
5
4
5
2
3
5
1
2
3
1
4
2
4
5
2
4
2
2
4
1
3
5
5
2
3
3
2
1
3
3
1
2
1
4
5
3
5
4
1
3
5
2
5
4
1
4
1
1
1
2
4
1
2
3
5
3
1
1
4
3
1
5
4
1
1
2
2
1
3
5
3
4
1
4
2
1
4
3
1
5
5
4
3
3
2
5
3
5
1
3
2
2
5
2
5
3
3
3
5
1
3
3
3
5
2
3
4
1
3
1
4
4
5
1
4
5
5
4
5
1
2
5
4
2
3
5
2
4
2
5
3
4
1
5
3
4
1
4
2
3
1
2
1
4
2
2
5
5
2
5
2
3
3
3
1
3
4
1
2
4
2
2
4
3
1
4
5
3
5
2
1
2
1
2
2
3
2
4
4
4
1
2
3
1
2
1
5
3
4
3
5
3
2
5
5
5
3
5
5
3
3
4
1
2
2
2
3
3
5
3
5
2
2
5
1
3
5
5
5
3
3
3
2
4
5
2
1
4
4
5
3
2
4
4
2
2
3
3
3
4
2
5
3
3
5
4
1
5
1
4
1
1
4
4
5
3
2
3
4
4
1
3
2
3
3
4
1
1
1
2
4
1
2
1
1
5
5
1
1
1
4
1
1
1
1
4
2
1
2
3
5
3
5
2
5
3
2
3
4
1
4
3
5
3
4
4
5
3
1
3
1
5
1
3
1
2
3
4
4
2
1
3
3
1
4
2
2
5
3
5
5
4
3
1
5
4
3
2
1
3
2
1
3
3
4
5
5
1
3
1
5
4
4
4
2
1
2
2
4
3
1
5
1
5
4
1
2
5
4
2
1
4
3
2
1
2
5
3
1
4
2
2
3
2
4
5
4
1
4
2
1
5
1
4
2
2
2
4
4
3
5
5
5
5
2
5
1
5
2
3
3
3
4
2
3
1
5
4
1
5
5
3
1
3
2
1
3
3
2
4
3
4
4
2
1
5
3
3
2
3
1
4
2
1
4
2
5
1
1
5
4
3
1
4
2
1
1
3
2
3
3
3
5
2
4
5
3
5
2
5
2
3
5
5
4
5
5
2
3
5
3
2
3
5
3
4
3
4
1
5
5
2
3
2
2
4
4
4
1
5
5
1
4
5
2
2
4
1
4
2
4
1
5
3
1
4
4
5
4
4
5
5
3
3
5
3
2
1
5
3
1
2
4
4
5
3
3
1
1
5
4
1
3
5
3
5
3
5
3
2
5
5
4
2
2
2
5
2
3
5
2
3
5
3
3
2
1
1
2
5
5
2
3
3
1
3
2
2
2
4
1
4
5
4
5
5
3
2
5
1
1
3
4
4
5
2
1
3
5
4
5
3
2
3
4
1
5
1
4
5
2
1
3
5
2
5
5
4
3
1
2
5
4
5
1
4
3
2
3
1
5
3
3
3
3
2
3
4
3
2
3
4
4
4
1
1
4
4
2
4
2
2
5
2
5
3
4
1
4
4
3
5
5
5
1
5
3
1
3
4
2
1
5
1
2
3
4
5
3
3
5
1
4
3
4
5
3
3
2
2
4
2
3
2
2
5
2
3
2
5
1
3
4
3
5
2
4
5
5
2
3
4
1
3
5
2
1
5
1
2
5
3
4
5
5
2
5
5
5
5
3
2
5
5
3
1
4
2
5
1
3
5
3
4
1
2
1
3
5
2
3
2
3
1
4
3
4
5
3
5
5
1
2
2
1
2
3
3
1
4
2
3
1
3
2
4
1
3
4
5
4
4
4
5
2
1
3
3
5
1
4
1
4
1
4
2
4
5
2
1
2
5
2
3
5
3
1
1
1
1
2
2
3
2
2
5
5
3
1
4
3
3
5
5
2
4
2
5
4
4
5
1
1
4
4
1
5
2
4
1
4
2
5
5
1
3
5
5
2
4
3
5
3
5
1
2
2
4
2
3
1
5
4
2
1
3
1
1
1
2
2
2
4
4
1
4
2
5
2
4
3
4
3
5
2
5
2
3
1
4
4
5
5
2
4
4
3
4
3
1
2
4
3
3
3
5
4
5
4
5
3
1
2
5
4
1
2
5
4
2
2
2
4
1
4
3
1
3
3
4
4
2
4
1
5
5
3
1
2
3
5
4
3
1
1
4
5
4
3
1
2
1
3
4
5
1
5
3
5
3
4
5
1
1
1
4
3
5
3
3
5
3
4
4
2
5
1
3
1
4
5
1
5
2
4
5
4
4
1
5
4
2
5
4
1
3
5
4
1
2
1
3
3
2
1
4
2
3
2
3
4
3
3
3
1
3
2
2
1
4
5
2
1
3
2
1
5
2
4
2
2
2
1
3
2
1
1
1
1
2
3
2
4
3
1
4
5
1
5
2
1
1
3
5
4
1
2
1
1
3
2
2
5
4
4
5
1
4
3
1
5
5
3
5
4
4
5
2
2
4
5
4
4
1
4
1
3
1
2
1
1
1
5
3
3
1
2
3
2
2
4
1
1
5
4
5
2
4
1
1
3
4
4
1
5
5
5
2
4
3
2
3
2
3
4
5
2
2
3
3
2
2
3
3
2
1
2
2
4
3
1
3
4
2
1
5
4
2
4
2
4
5
1
1
2
1
1
3
3
4
3
4
3
1
5
1
4
3
4
2
5
2
3
4
5
2
3
3
3
2
4
1
1
4
5
3
1
2
4
4
2
2
2
1
5
2
5
3
2
5
4
5
4
2
1
2
2
5
4
1
3
4
5
1
3
2
2
1
1
5
2
2
1
1
3
4
2
4
2
4
3
1
1
1
3
4
2
5
2
1
2
5
3
3
2
1
2
3
3
4
4
2
4
2
5
5
3
5
3
2
5
1
4
1
4
4
5
3
4
1
3
3
5
4
5
2
5
5
2
1
4
1
3
5
1
5
3
2
4
5
3
3
1
3
5
5
4
4
4
2
2
3
2
4
2
2
1
2
5
4
1
1
3
4
4
4
4
3
5
4
2
5
4
5
5
2
4
5
3
4
3
1
2
4
4
3
2
1
5
4
3
5
2
1
2
1
5
1
1
5
4
5
1
1
3
3
5
2
5
5
3
5
1
3
1
1
3
5
2
5
1
1
4
4
3
4
2
3
4
3
3
1
3
3
5
5
1
2
1
3
4
3
4
5
3
1
4
4
1
3
4
2
4
2
1
5
2
4
4
4
2
5
2
2
1
3
2
2
4
1
5
2
2
2
5
4
3
5
5
2
2
5
2
5
2
2
1
2
5
4
1
3
4
3
4
5
3
2
1
1
5
5
1
5
2
1
3
4
2
5
3
2
2
5
3
1
4
2
4
2
2
2
2
4
5
5
4
3
5
1
5
1
3
2
3
5
5
1
2
3
2
2
1
3
4
4
2
1
5
4
2
4
5
2
5
5
1
4
2
2
5
4
4
5
1
5
4
4
3
5
5
3
4
2
4
3
5
5
2
4
5
4
4
1
5
2
3
2
1
1
1
1
2
1
5
3
1
1
5
2
4
4
2
5
2
4
5
2
5
3
3
2
5
2
4
2
2
5
3
4
3
4
4
5
3
2
5
2
1
5
3
4
5
3
4
1
1
4
2
4
3
2
2
3
1
2
3
4
5
1
2
4
2
2
3
5
4
3
1
5
4
3
1
4
5
5
3
4
2
5
3
4
2
1
2
3
4
5
4
5
1
1
4
1
4
5
1
5
1
1
2
3
1
5
2
3
5
1
5
5
4
2
2
4
4
3
3
3
3
5
4
1
2
5
1
4
3
2
3
1
3
2
1
3
4
3
3
4
5
3
2
3
3
4
4
5
2
5
5
2
5
2
2
1
5
1
2
5
1
1
1
1
3
2
2
5
5
2
4
2
4
4
3
2
4
5
4
3
1
2
4
2
2
2
5
5
3
5
4
2
1
2
2
2
4
4
2
1
3
1
3
4
3
1
1
1
1
5
4
2
1
5
1
2
4
5
5
4
5
4
3
1
1
5
3
4
2
2
4
1
3
1
3
3
5
1
2
3
2
1
2
3
3
5
1
2
4
1
1
5
5
3
4
5
1
4
4
3
5
4
3
5
4
1
4
5
1
1
3
2
2
2
5
5
3
5
3
2
4
2
4
4
1
3
1
1
1
2
2
2
2
2
2
5
3
1
4
4
2
2
2
5
1
1
3
1
2
2
1
5
4
4
3
1
4
5
4
2
2
3
1
2
3
1
5
5
1
2
2
1
5
1
4
3
3
2
2
1
2
4
3
5
4
5
2
3
1
5
2
1
3
5
4
3
2
3
3
4
1
1
5
5
4
5
3
2
2
2
3
4
4
1
5
2
3
3
2
5
3
1
5
5
5
1
5
1
5
4
2
4
5
4
4
1
4
3
1
4
2
3
3
1
1
1
4
2
3
4
5
5
4
3
4
5
5
3
4
2
1
3
3
5
2
2
1
4
1
3
1
3
5
5
5
1
2
1
1
1
3
3
2
1
3
5
4
5
4
1
4
1
3
5
4
1
2
1
1
4
1
2
5
1
2
3
5
2
1
4
2
2
5
3
1
1
4
1
5
2
5
4
4
4
2
1
4
5
5
1
2
4
2
4
2
2
4
3
5
1
4
5
3
2
4
1
1
3
1
4
2
5
1
1
2
5
2
3
2
2
5
1
1
3
4
5
1
5
4
3
2
3
3
5
2
3
1
3
3
2
1
5
3
1
1
3
2
1
3
2
5
5
5
2
4
1
1
2
4
3
3
5
5
2
4
5
2
3
1
4
3
3
2
3
3
4
3
2
1
1
5
5
2
5
1
4
3
2
3
2
2
2
1
3
2
1
3
4
2
2
2
2
4
2
3
1
2
3
2
4
1
4
3
5
5
5
3
1
5
1
1
3
2
5
3
2
1
2
4
3
4
4
4
1
4
4
5
4
4
1
4
4
3
1
5
4
3
2
1
4
1
4
5
4
3
2
4
2
3
4
4
2
1
2
4
5
1
3
4
3
2
5
3
4
1
2
3
5
4
4
5
5
2
2
2
3
5
5
5
5
5
2
3
3
5
2
4
1
2
2
2
5
2
1
1
1
5
4
5
4
1
3
2
1
5
2
1
2
5
2
4
1
1
4
3
3
4
2
5
3
5
5
5
2
3
4
5
1
4
3
2
5
4
4
5
1
5
5
5
3
2
3
3
4
4
3
3
4
3
3
4
3
5
2
1
5
2
2
2
3
5
2
5
4
1
1
5
5
5
4
4
4
5
2
3
1
3
1
2
2
1
3
5
3
2
4
3
2
3
3
5
1
3
5
2
1
1
3
1
5
1
1
3
5
2
1
5
2
2
1
1
5
3
3
4
5
5
2
5
5
2
3
1
3
4
3
1
5
2
4
4
4
5
4
1
4
5
2
3
4
2
1
4
2
4
4
2
1
5
2
4
1
5
2
5
1
2
2
5
2
5
1
3
4
4
1
5
5
4
1
5
2
2
2
3
1
1
3
1
1
5
2
4
1
5
5
2
1
3
3
1
4
3
4
5
2
2
4
1
4
2
4
5
4
2
2
4
3
2
5
5
4
4
1
2
5
2
3
4
3

In [30]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
6,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
7,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
8,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
9,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15

In [48]:

# df.reset_index(inplace = True)
# df.drop(columns= "index",inplace =True)

df2 = df

In [68]:
# for x in df2.index:
#     print(df2.loc[x,"Price Per Unit"])

# df2["Price Per Unit"] = df2["Price Per Unit"].replace("0.0","UNKNOWN")

# df2["Price Per Unit"].value_counts().get("UNKNOWN",0)

for x in df2.index:
    print(df2.loc[x,"Price Per Unit"])
# df2.head(30)

2.0
3.0
1.0
5.0
2.0
4.0
5.0
4.0
4.0
5.0
3.0
3.0
3.0
4.0
4.0
4.0
1.0
3.0
3.0
4.0
4.0
5.0
3.0
5.0
4.0
4.0
1.0
3.0
1.5
3.0
4.0
2.0
3.0
2.0
3.0
3.0
5.0
1.5
3.0
5.0
5.0
2.0
3.0
2.0
3.0
5.0
1.0
1.0
5.0
5.0
2.0
1.5
4.0
3.0
4.0
3.0
3.0
1.5
2.0
5.0
1.5
UNKNOWN
3.0
2.0
5.0
UNKNOWN
UNKNOWN
4.0
3.0
1.0
1.0
1.0
4.0
4.0
3.0
3.0
4.0
2.0
3.0
1.0
ERROR
2.0
2.0
1.0
4.0
4.0
5.0
5.0
2.0
3.0
1.0
5.0
1.0
UNKNOWN
5.0
3.0
3.0
4.0
4.0
1.5
1.5
4.0
3.0
3.0
5.0
1.5
5.0
1.0
4.0
4.0
4.0
1.5
4.0
4.0
4.0
4.0
3.0
4.0
1.5
4.0
1.0
1.5
4.0
1.5
3.0
3.0
3.0
1.5
4.0
1.5
4.0
5.0
1.0
1.0
2.0
5.0
4.0
4.0
5.0
3.0
3.0
4.0
1.5
4.0
4.0
2.0
3.0
2.0
4.0
4.0
1.0
1.5
3.0
4.0
4.0
5.0
3.0
2.0
1.0
1.0
5.0
2.0
2.0
3.0
1.0
3.0
4.0
1.5
3.0
5.0
3.0
1.5
2.0
1.0
1.0
3.0
1.0
ERROR
5.0
3.0
2.0
1.0
4.0
3.0
3.0
2.0
2.0
4.0
4.0
5.0
4.0
3.0
3.0
ERROR
4.0
UNKNOWN
1.0
3.0
1.5
2.0
1.5
2.0
2.0
3.0
4.0
5.0
1.0
5.0
3.0
4.0
1.0
1.5
3.0
1.5
1.0
4.0
4.0
5.0
3.0
1.5
5.0
4.0
4.0
1.0
1.5
4.0
3.0
4.0
1.0
4.0
3.0
1.0
4.0
3.0
1.5
5.0
1.0
3.0
4.0
4.0
1.5
3.0
5.0
1.5
1.0
ERROR
4.0
2.0
4.0
1.0
ERROR
4.0
2.0
5.0
4.0
1.0
2.0
4.0
2.0
3.0
5.0
3.0
4.0
1.5
1.0
5.0
5.0
5.0
5.0
1.0
5.0
1.0
3.0
1.0
3.0
4.0
4.0
4.0
4.0
4.0
4.0
5.0
4.0
4.0
3.0
5.0
1.5
3.0
3.0
1.0
4.0
3.0
ERROR
3.0
5.0
3.0
2.0
4.0
1.0
3.0
3.0
5.0
3.0
5.0
5.0
4.0
2.0
3.0
4.0
3.0
2.0
4.0
5.0
4.0
4.0
1.5
4.0
UNKNOWN
1.0
1.5
2.0
1.0
5.0
4.0
2.0
UNKNOWN
3.0
3.0
4.0
1.5
1.5
UNKNOWN
3.0
UNKNOWN
4.0
1.0
4.0
2.0
1.0
5.0
3.0
UNKNOWN
3.0
1.0
4.0
1.0
4.0
ERROR
2.0
4.0
1.0
3.0
2.0
1.5
5.0
2.0
1.5
1.0
1.0
3.0
4.0
1.5
UNKNOWN
3.0
2.0
3.0
4.0
4.0
3.0
ERROR
3.0
1.0
3.0
1.5
2.0
3.0
4.0
1.0
3.0
1.0
1.5
ERROR
4.0
UNKNOWN
4.0
5.0
UNKNOWN
4.0
2.0
5.0
5.0
5.0
3.0
3.0
1.5
1.5
UNKNOWN
3.0
2.0
3.0
3.0
2.0
4.0
3.0
1.5
3.0
1.5
5.0
5.0
5.0
3.0
1.5
1.5
4.0
4.0
1.5
5.0
3.0
4.0
3.0
4.0
2.0
5.0
4.0
2.0
1.5
5.0
3.0
1.0
5.0
1.5
1.0
4.0
1.5
4.0
4.0
2.0
4.0
4.0
ERROR
2.0
3.0
5.0
3.0
4.0
3.0
1.0
3.0
3.0
3.0
3.0
5.0
4.0
3.0
5.0
4.0
5.0
4.0
3.0
1.0
1.5
3.0
4.0
3.0
1.0
3.0
4.0
3.0
5.0
1.0
5.0
1.0
5.0
1.0
4.0
1.5
1.0
5.0
3.0
3.0
4.0
3.0
5.0
2.0
1.5
4.0
5.0
3.0
4.0
4.0
3.0
5.0
4.0
4.0
3.0
3.0
4.0
4.0
4.0
2.0
4.0
3.0
1.0
4.0
2.0
3.0
4.0
2.0
ERROR
2.0
4.0
2.0
3.0
2.0
2.0
4.0
5.0
5.0
5.0
1.0
3.0
1.0
1.5
5.0
1.0
4.0
1.5
4.0
4.0
4.0
3.0
4.0
1.0
1.0
4.0
2.0
4.0
3.0
ERROR
4.0
2.0
3.0
1.5
4.0
4.0
2.0
2.0
3.0
ERROR
4.0
4.0
1.0
1.0
3.0
5.0
2.0
2.0
3.0
1.5
4.0
5.0
5.0
3.0
3.0
3.0
3.0
2.0
4.0
1.0
1.0
5.0
1.5
UNKNOWN
1.0
1.5
5.0
3.0
4.0
4.0
5.0
1.0
2.0
1.0
4.0
3.0
2.0
2.0
4.0
3.0
4.0
UNKNOWN
3.0
3.0
1.0
3.0
3.0
3.0
4.0
2.0
4.0
4.0
ERROR
3.0
ERROR
4.0
3.0
ERROR
1.5
1.5
3.0
4.0
1.5
1.0
4.0
3.0
4.0
1.5
5.0
3.0
3.0
3.0
4.0
3.0
3.0
3.0
1.5
3.0
4.0
3.0
4.0
1.5
3.0
1.0
3.0
4.0
4.0
2.0
1.5
3.0
5.0
3.0
3.0
3.0
5.0
3.0
5.0
4.0
5.0
2.0
1.5
5.0
1.0
5.0
3.0
4.0
2.0
1.0
2.0
1.0
3.0
1.5
3.0
1.5
1.5
4.0
1.0
5.0
5.0
3.0
5.0
4.0
2.0
2.0
4.0
1.5
5.0
1.5
3.0
3.0
3.0
3.0
4.0
1.5
3.0
5.0
4.0
3.0
5.0
2.0
2.0
3.0
UNKNOWN
4.0
3.0
1.0
3.0
1.0
4.0
5.0
1.0
5.0
3.0
2.0
5.0
1.5
3.0
3.0
3.0
4.0
5.0
1.5
4.0
1.5
4.0
1.0
4.0
1.5
4.0
3.0
4.0
2.0
2.0
3.0
1.0
4.0
3.0
1.5
4.0
4.0
3.0
1.0
5.0
4.0
1.5
4.0
1.0
3.0
4.0
3.0
2.0
4.0
3.0
4.0
1.5
3.0
3.0
3.0
3.0
1.5
1.5
1.5
1.5
4.0
3.0
ERROR
3.0
3.0
1.0
3.0
2.0
3.0
2.0
5.0
4.0
3.0
1.0
5.0
3.0
4.0
1.5
4.0
3.0
2.0
4.0
4.0
2.0
4.0
3.0
4.0
ERROR
2.0
5.0
1.0
4.0
1.0
1.0
4.0
2.0
1.5
1.5
UNKNOWN
3.0
3.0
5.0
1.0
3.0
3.0
4.0
1.0
5.0
1.0
3.0
2.0
4.0
3.0
4.0
1.0
4.0
5.0
4.0
3.0
4.0
4.0
1.5
4.0
1.5
4.0
1.5
2.0
3.0
1.5
3.0
5.0
3.0
5.0
1.0
3.0
2.0
1.5
4.0
5.0
5.0
3.0
4.0
4.0
1.0
3.0
3.0
1.5
2.0
2.0
3.0
4.0
3.0
1.0
1.5
1.5
4.0
4.0
1.5
UNKNOWN
3.0
3.0
2.0
4.0
2.0
5.0
5.0
1.0
3.0
4.0
2.0
4.0
3.0
4.0
4.0
5.0
3.0
1.0
4.0
4.0
3.0
4.0
3.0
1.0
1.0
3.0
5.0
1.5
2.0
2.0
4.0
3.0
ERROR
4.0
4.0
4.0
1.5
3.0
3.0
2.0
4.0
ERROR
UNKNOWN
3.0
4.0
4.0
4.0
5.0
1.5
3.0
4.0
2.0
3.0
5.0
2.0
2.0
UNKNOWN
5.0
1.5
3.0
4.0
3.0
2.0
2.0
5.0
4.0
4.0
5.0
ERROR
5.0
4.0
2.0
3.0
4.0
5.0
1.5
UNKNOWN
4.0
3.0
2.0
3.0
4.0
4.0
4.0
4.0
2.0
5.0
3.0
4.0
1.5
UNKNOWN
3.0
3.0
5.0
5.0
1.5
1.5
3.0
2.0
1.0
5.0
ERROR
3.0
2.0
3.0
5.0
1.0
3.0
1.0
5.0
5.0
4.0
4.0
4.0
2.0
3.0
3.0
ERROR
4.0
1.0
4.0
4.0
1.5
3.0
5.0
4.0
5.0
5.0
3.0
2.0
4.0
4.0
2.0
2.0
3.0
4.0
1.0
UNKNOWN
1.5
4.0
3.0
1.0
4.0
2.0
5.0
1.5
5.0
3.0
4.0
4.0
3.0
2.0
1.5
1.5
2.0
2.0
5.0
UNKNOWN
4.0
1.5
4.0
2.0
1.0
4.0
1.0
4.0
1.0
4.0
1.5
1.5
2.0
5.0
4.0
4.0
1.5
4.0
2.0
3.0
3.0
1.5
ERROR
1.5
4.0
5.0
3.0
2.0
1.0
1.0
2.0
2.0
1.0
2.0
UNKNOWN
4.0
2.0
5.0
3.0
4.0
5.0
4.0
3.0
1.5
2.0
4.0
4.0
3.0
1.5
1.0
3.0
1.0
UNKNOWN
1.5
4.0
2.0
1.0
5.0
3.0
3.0
3.0
1.0
4.0
4.0
2.0
2.0
1.5
4.0
5.0
5.0
2.0
3.0
4.0
4.0
3.0
3.0
5.0
5.0
1.5
3.0
3.0
1.0
1.0
4.0
1.5
1.5
2.0
1.0
1.0
3.0
5.0
3.0
1.0
3.0
4.0
3.0
1.0
1.0
3.0
3.0
1.0
3.0
1.5
2.0
2.0
2.0
4.0
2.0
ERROR
4.0
4.0
3.0
1.0
4.0
3.0
2.0
1.0
3.0
3.0
3.0
3.0
1.5
5.0
5.0
1.0
3.0
2.0
1.5
3.0
3.0
5.0
4.0
4.0
2.0
3.0
1.0
3.0
2.0
3.0
3.0
4.0
2.0
1.0
5.0
4.0
2.0
3.0
3.0
4.0
3.0
4.0
4.0
1.0
4.0
3.0
4.0
4.0
3.0
3.0
3.0
3.0
4.0
1.0
2.0
1.0
1.0
5.0
4.0
4.0
5.0
1.5
1.0
1.5
5.0
3.0
1.5
3.0
3.0
ERROR
1.0
3.0
4.0
5.0
3.0
2.0
3.0
4.0
1.5
1.5
4.0
4.0
3.0
2.0
3.0
4.0
4.0
1.0
3.0
2.0
4.0
5.0
4.0
5.0
4.0
1.5
1.5
4.0
4.0
5.0
4.0
4.0
3.0
2.0
1.5
5.0
2.0
2.0
3.0
3.0
1.0
1.0
3.0
5.0
5.0
4.0
2.0
1.5
1.5
3.0
3.0
4.0
5.0
4.0
3.0
1.5
3.0
3.0
5.0
3.0
1.5
4.0
3.0
3.0
1.5
3.0
1.5
1.0
3.0
4.0
2.0
1.0
4.0
1.0
4.0
2.0
4.0
4.0
5.0
3.0
4.0
4.0
1.5
3.0
3.0
5.0
5.0
5.0
1.0
1.0
3.0
3.0
5.0
2.0
5.0
3.0
3.0
3.0
4.0
5.0
1.0
4.0
3.0
3.0
3.0
2.0
4.0
4.0
3.0
3.0
1.5
3.0
4.0
1.0
1.0
3.0
4.0
1.5
5.0
3.0
4.0
1.5
5.0
3.0
3.0
1.5
2.0
3.0
1.5
4.0
3.0
3.0
2.0
2.0
1.0
4.0
3.0
3.0
4.0
3.0
2.0
1.5
1.5
5.0
4.0
4.0
4.0
3.0
3.0
3.0
3.0
1.0
ERROR
3.0
3.0
3.0
1.0
2.0
1.5
3.0
2.0
4.0
4.0
3.0
3.0
3.0
3.0
5.0
1.0
1.0
4.0
4.0
5.0
1.0
ERROR
5.0
4.0
5.0
5.0
5.0
4.0
3.0
4.0
3.0
3.0
1.0
4.0
2.0
4.0
4.0
3.0
5.0
2.0
3.0
5.0
3.0
1.5
4.0
3.0
3.0
4.0
1.0
1.0
1.0
1.0
3.0
1.0
4.0
UNKNOWN
4.0
4.0
3.0
3.0
3.0
5.0
5.0
4.0
4.0
1.5
5.0
1.5
1.5
3.0
1.5
3.0
4.0
3.0
1.5
4.0
4.0
3.0
1.0
3.0
1.0
4.0
3.0
3.0
UNKNOWN
5.0
4.0
3.0
4.0
3.0
UNKNOWN
1.0
4.0
1.0
1.0
4.0
4.0
3.0
1.0
3.0
2.0
3.0
4.0
2.0
4.0
3.0
4.0
4.0
4.0
3.0
1.5
4.0
3.0
3.0
3.0
1.5
1.5
4.0
2.0
1.5
ERROR
3.0
2.0
5.0
4.0
1.5
2.0
1.5
1.0
4.0
2.0
2.0
3.0
3.0
5.0
1.0
1.0
1.5
4.0
5.0
3.0
4.0
3.0
3.0
2.0
1.5
3.0
3.0
4.0
3.0
4.0
5.0
5.0
1.5
3.0
4.0
3.0
4.0
3.0
2.0
4.0
3.0
1.5
1.0
5.0
5.0
4.0
1.5
3.0
1.0
3.0
1.0
ERROR
3.0
4.0
3.0
2.0
1.0
3.0
3.0
1.0
4.0
1.5
3.0
4.0
1.5
4.0
5.0
5.0
3.0
4.0
1.0
3.0
5.0
4.0
2.0
ERROR
4.0
2.0
3.0
1.5
5.0
1.5
1.5
5.0
1.5
5.0
4.0
2.0
5.0
1.0
3.0
4.0
1.0
5.0
3.0
ERROR
3.0
3.0
2.0
2.0
3.0
1.0
4.0
2.0
2.0
4.0
1.5
1.5
3.0
1.5
4.0
1.5
1.5
1.5
5.0
1.5
4.0
4.0
4.0
4.0
3.0
1.0
1.0
3.0
5.0
1.5
1.0
1.5
1.5
1.0
4.0
2.0
1.0
5.0
4.0
2.0
1.5
1.5
5.0
1.5
4.0
4.0
2.0
1.0
1.0
4.0
4.0
1.5
5.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
5.0
4.0
4.0
1.0
4.0
4.0
1.5
1.5
1.5
3.0
5.0
2.0
3.0
1.0
2.0
5.0
3.0
5.0
4.0
1.0
4.0
1.0
1.0
UNKNOWN
2.0
4.0
3.0
4.0
2.0
1.0
3.0
1.0
4.0
3.0
1.0
5.0
1.0
3.0
4.0
2.0
4.0
1.5
2.0
3.0
3.0
3.0
1.0
3.0
3.0
3.0
2.0
1.0
2.0
1.5
2.0
1.0
3.0
1.0
4.0
3.0
2.0
3.0
4.0
1.0
2.0
5.0
4.0
3.0
5.0
2.0
3.0
5.0
3.0
5.0
2.0
3.0
3.0
5.0
1.0
1.5
2.0
1.0
1.5
4.0
3.0
3.0
1.0
3.0
5.0
1.0
1.0
3.0
5.0
4.0
1.0
3.0
1.5
1.0
3.0
2.0
4.0
3.0
5.0
UNKNOWN
3.0
4.0
2.0
3.0
1.5
1.0
1.0
1.0
3.0
3.0
5.0
1.5
2.0
4.0
5.0
3.0
1.0
2.0
5.0
UNKNOWN
2.0
5.0
2.0
1.0
1.5
5.0
1.5
1.0
4.0
3.0
3.0
3.0
1.5
4.0
4.0
1.5
3.0
1.0
2.0
2.0
3.0
1.0
2.0
1.5
1.5
4.0
2.0
4.0
1.5
4.0
4.0
1.0
4.0
3.0
5.0
2.0
5.0
1.5
4.0
3.0
3.0
4.0
3.0
4.0
1.0
3.0
5.0
1.0
2.0
3.0
5.0
3.0
4.0
3.0
3.0
1.0
4.0
1.0
3.0
5.0
5.0
3.0
5.0
3.0
4.0
3.0
1.5
4.0
2.0
3.0
1.0
3.0
4.0
3.0
1.5
UNKNOWN
3.0
1.0
2.0
3.0
1.5
4.0
4.0
1.0
3.0
3.0
5.0
4.0
3.0
1.5
4.0
3.0
1.0
5.0
3.0
1.0
1.0
4.0
1.0
4.0
1.5
1.0
2.0
1.5
4.0
5.0
5.0
4.0
5.0
UNKNOWN
3.0
3.0
1.0
3.0
2.0
2.0
5.0
4.0
3.0
1.5
1.0
3.0
4.0
2.0
4.0
4.0
3.0
1.0
4.0
1.5
4.0
1.0
2.0
5.0
5.0
4.0
4.0
1.0
5.0
UNKNOWN
3.0
1.5
4.0
UNKNOWN
1.0
5.0
5.0
2.0
4.0
4.0
1.0
3.0
3.0
3.0
3.0
3.0
1.0
1.5
1.0
2.0
3.0
4.0
1.0
4.0
4.0
3.0
3.0
4.0
4.0
3.0
4.0
3.0
1.0
UNKNOWN
2.0
1.5
3.0
3.0
1.5
ERROR
4.0
2.0
3.0
1.0
4.0
5.0
3.0
4.0
5.0
3.0
UNKNOWN
3.0
4.0
1.5
3.0
2.0
4.0
1.5
4.0
1.0
3.0
1.5
3.0
1.0
ERROR
1.5
2.0
2.0
4.0
4.0
1.0
2.0
4.0
1.5
1.0
4.0
5.0
4.0
4.0
1.0
1.5
4.0
1.5
3.0
4.0
4.0
3.0
4.0
4.0
3.0
1.5
4.0
ERROR
1.0
1.5
5.0
4.0
3.0
3.0
4.0
3.0
4.0
1.0
3.0
4.0
4.0
5.0
4.0
1.5
5.0
2.0
4.0
3.0
3.0
4.0
1.0
2.0
4.0
3.0
4.0
4.0
5.0
4.0
4.0
2.0
1.5
5.0
UNKNOWN
1.5
5.0
1.0
5.0
1.5
4.0
4.0
1.5
5.0
4.0
1.0
3.0
3.0
3.0
4.0
3.0
ERROR
1.5
1.5
1.5
4.0
3.0
1.0
3.0
1.0
4.0
3.0
1.0
1.0
4.0
3.0
4.0
3.0
2.0
2.0
3.0
3.0
1.5
4.0
1.0
3.0
1.0
3.0
5.0
3.0
3.0
5.0
5.0
1.5
5.0
1.5
5.0
4.0
3.0
4.0
4.0
5.0
3.0
4.0
5.0
4.0
UNKNOWN
4.0
1.5
1.0
4.0
3.0
4.0
4.0
ERROR
5.0
3.0
3.0
5.0
4.0
3.0
1.5
2.0
4.0
2.0
1.5
2.0
1.5
2.0
3.0
4.0
1.5
4.0
3.0
4.0
2.0
2.0
5.0
2.0
4.0
3.0
4.0
1.5
5.0
3.0
3.0
4.0
1.0
1.5
1.0
2.0
3.0
3.0
1.0
3.0
1.0
3.0
5.0
3.0
4.0
2.0
3.0
3.0
2.0
3.0
5.0
1.5
4.0
3.0
2.0
1.5
5.0
2.0
4.0
1.0
3.0
4.0
3.0
1.0
2.0
4.0
5.0
4.0
3.0
2.0
5.0
1.0
4.0
1.5
2.0
4.0
1.0
5.0
1.0
4.0
4.0
5.0
2.0
4.0
5.0
5.0
4.0
ERROR
1.0
3.0
1.5
3.0
3.0
4.0
4.0
4.0
1.5
4.0
3.0
3.0
1.5
3.0
2.0
5.0
5.0
5.0
5.0
1.0
3.0
3.0
4.0
3.0
ERROR
5.0
3.0
1.0
5.0
2.0
4.0
3.0
ERROR
1.5
4.0
4.0
ERROR
3.0
1.0
4.0
1.5
3.0
1.0
4.0
3.0
3.0
1.5
4.0
4.0
3.0
5.0
3.0
3.0
3.0
3.0
3.0
UNKNOWN
3.0
2.0
2.0
4.0
4.0
4.0
5.0
5.0
5.0
1.0
3.0
3.0
5.0
1.0
4.0
2.0
4.0
1.0
3.0
2.0
1.5
ERROR
5.0
5.0
1.0
1.5
4.0
1.0
1.0
3.0
ERROR
4.0
4.0
4.0
1.5
2.0
1.0
1.0
2.0
5.0
5.0
1.5
4.0
ERROR
4.0
3.0
4.0
2.0
4.0
4.0
2.0
4.0
UNKNOWN
3.0
3.0
1.0
1.0
2.0
5.0
3.0
4.0
3.0
ERROR
1.0
1.5
4.0
1.5
3.0
3.0
4.0
3.0
2.0
2.0
2.0
2.0
4.0
2.0
2.0
3.0
1.5
4.0
1.0
1.5
4.0
1.5
4.0
3.0
1.0
4.0
1.5
2.0
4.0
3.0
2.0
4.0
4.0
3.0
3.0
3.0
2.0
1.0
1.0
1.0
2.0
2.0
1.5
1.0
1.5
1.5
1.5
4.0
4.0
4.0
2.0
5.0
5.0
5.0
2.0
3.0
5.0
3.0
2.0
1.5
5.0
4.0
3.0
4.0
4.0
1.5
2.0
1.5
1.5
1.0
1.0
4.0
4.0
5.0
4.0
UNKNOWN
4.0
5.0
UNKNOWN
1.0
5.0
4.0
4.0
3.0
4.0
4.0
2.0
3.0
2.0
4.0
3.0
5.0
5.0
4.0
4.0
4.0
3.0
2.0
3.0
3.0
1.5
3.0
1.0
4.0
2.0
2.0
1.5
3.0
1.0
5.0
UNKNOWN
2.0
4.0
1.0
3.0
2.0
4.0
1.0
1.0
1.0
1.0
5.0
5.0
3.0
3.0
1.5
4.0
5.0
1.0
3.0
1.5
4.0
5.0
2.0
1.0
3.0
4.0
UNKNOWN
4.0
1.0
2.0
2.0
1.0
ERROR
3.0
4.0
1.5
4.0
1.5
4.0
5.0
4.0
1.0
1.0
3.0
1.0
3.0
3.0
4.0
2.0
1.0
1.5
5.0
3.0
3.0
1.0
4.0
2.0
3.0
1.0
2.0
3.0
3.0
4.0
4.0
4.0
1.0
1.5
5.0
4.0
3.0
4.0
3.0
3.0
3.0
3.0
4.0
1.0
2.0
5.0
1.0
5.0
1.0
3.0
5.0
3.0
4.0
3.0
4.0
5.0
1.5
4.0
4.0
3.0
1.0
3.0
2.0
1.0
1.5
1.5
5.0
5.0
2.0
4.0
3.0
1.0
3.0
5.0
3.0
1.5
1.0
4.0
3.0
3.0
1.5
1.0
1.5
1.0
1.0
5.0
2.0
4.0
1.5
1.0
4.0
3.0
3.0
1.5
3.0
1.0
4.0
ERROR
4.0
3.0
1.5
1.5
4.0
1.5
1.5
1.5
3.0
5.0
3.0
2.0
2.0
2.0
5.0
4.0
4.0
4.0
3.0
5.0
1.0
3.0
4.0
5.0
1.5
1.0
5.0
3.0
3.0
4.0
1.5
1.5
1.0
5.0
3.0
3.0
5.0
3.0
3.0
4.0
2.0
3.0
5.0
5.0
2.0
5.0
4.0
ERROR
3.0
3.0
1.0
3.0
UNKNOWN
2.0
4.0
ERROR
3.0
1.0
2.0
1.0
1.0
3.0
1.5
1.0
4.0
5.0
3.0
4.0
1.0
1.5
3.0
2.0
1.0
1.0
2.0
5.0
ERROR
5.0
3.0
3.0
5.0
3.0
3.0
3.0
ERROR
2.0
4.0
ERROR
1.5
3.0
2.0
4.0
1.0
1.0
3.0
5.0
3.0
3.0
3.0
3.0
4.0
5.0
1.0
3.0
1.5
2.0
1.5
4.0
3.0
1.5
ERROR
4.0
2.0
3.0
1.5
2.0
4.0
4.0
3.0
5.0
4.0
1.0
3.0
5.0
3.0
3.0
1.0
3.0
2.0
1.0
5.0
3.0
4.0
4.0
3.0
5.0
3.0
2.0
4.0
3.0
1.0
3.0
3.0
3.0
4.0
1.0
3.0
4.0
4.0
1.0
1.0
2.0
5.0
2.0
3.0
4.0
1.0
1.5
4.0
3.0
3.0
ERROR
3.0
3.0
5.0
3.0
4.0
2.0
1.5
3.0
1.5
1.0
1.5
5.0
1.0
1.0
1.0
3.0
2.0
UNKNOWN
4.0
3.0
4.0
3.0
3.0
2.0
2.0
1.5
2.0
1.0
2.0
4.0
ERROR
5.0
5.0
5.0
5.0
4.0
UNKNOWN
5.0
3.0
3.0
3.0
1.0
1.0
2.0
4.0
3.0
4.0
3.0
3.0
4.0
4.0
1.5
1.5
4.0
4.0
3.0
UNKNOWN
3.0
4.0
1.0
4.0
4.0
1.5
1.5
3.0
UNKNOWN
1.5
5.0
4.0
1.5
3.0
4.0
1.0
3.0
1.5
1.0
1.0
3.0
5.0
1.0
2.0
4.0
1.0
4.0
5.0
3.0
1.0
1.0
4.0
4.0
3.0
1.5
4.0
1.5
1.5
2.0
4.0
4.0
2.0
3.0
1.0
5.0
4.0
4.0
2.0
3.0
1.5
5.0
1.5
4.0
2.0
2.0
3.0
5.0
5.0
1.0
3.0
4.0
3.0
4.0
4.0
4.0
4.0
UNKNOWN
2.0
4.0
1.0
2.0
2.0
4.0
1.5
1.0
ERROR
5.0
1.5
2.0
4.0
2.0
3.0
2.0
3.0
3.0
3.0
1.5
5.0
4.0
1.5
1.0
3.0
1.5
UNKNOWN
4.0
3.0
3.0
1.5
4.0
5.0
3.0
UNKNOWN
3.0
2.0
4.0
3.0
1.5
2.0
1.5
3.0
3.0
4.0
5.0
1.5
4.0
4.0
1.0
ERROR
4.0
3.0
1.5
3.0
3.0
3.0
2.0
ERROR
3.0
2.0
3.0
4.0
3.0
4.0
1.0
1.5
1.5
2.0
4.0
5.0
2.0
1.5
4.0
3.0
1.5
5.0
3.0
3.0
5.0
2.0
4.0
4.0
1.0
2.0
1.0
4.0
ERROR
4.0
3.0
4.0
2.0
4.0
1.0
2.0
5.0
4.0
1.0
3.0
4.0
3.0
1.0
2.0
4.0
3.0
2.0
3.0
1.0
2.0
5.0
3.0
3.0
3.0
4.0
5.0
1.0
4.0
1.5
1.5
4.0
5.0
3.0
3.0
2.0
5.0
4.0
3.0
1.0
2.0
5.0
4.0
4.0
4.0
4.0
2.0
4.0
4.0
3.0
3.0
4.0
1.0
3.0
1.0
4.0
1.5
4.0
3.0
1.5
1.0
4.0
5.0
5.0
3.0
4.0
2.0
3.0
3.0
4.0
3.0
3.0
4.0
4.0
2.0
1.0
3.0
1.5
3.0
ERROR
3.0
1.5
4.0
1.5
4.0
5.0
1.0
3.0
1.5
3.0
4.0
1.0
2.0
5.0
3.0
4.0
ERROR
5.0
4.0
3.0
3.0
3.0
4.0
4.0
1.0
4.0
4.0
5.0
3.0
2.0
3.0
4.0
3.0
2.0
3.0
3.0
5.0
3.0
1.0
1.0
2.0
UNKNOWN
4.0
3.0
1.5
1.0
1.0
3.0
4.0
4.0
4.0
1.0
1.5
3.0
ERROR
4.0
1.5
2.0
5.0
3.0
5.0
2.0
1.0
5.0
1.5
5.0
1.0
3.0
4.0
1.0
2.0
3.0
3.0
3.0
1.5
2.0
3.0
2.0
1.5
3.0
1.0
3.0
3.0
2.0
3.0
5.0
5.0
4.0
3.0
3.0
4.0
1.5
4.0
3.0
4.0
3.0
2.0
1.0
4.0
4.0
1.5
3.0
4.0
1.0
2.0
3.0
3.0
3.0
5.0
3.0
5.0
3.0
1.5
5.0
4.0
4.0
1.0
3.0
4.0
2.0
3.0
3.0
1.5
5.0
4.0
3.0
2.0
3.0
4.0
1.0
1.0
3.0
2.0
2.0
3.0
1.5
ERROR
5.0
4.0
3.0
5.0
5.0
4.0
4.0
4.0
4.0
ERROR
3.0
1.0
2.0
3.0
4.0
3.0
1.5
1.5
1.5
ERROR
3.0
1.5
5.0
1.5
5.0
1.0
1.0
1.5
1.5
4.0
3.0
1.5
5.0
1.0
4.0
1.0
4.0
4.0
5.0
3.0
1.5
1.0
3.0
4.0
3.0
4.0
1.5
3.0
4.0
4.0
3.0
1.5
2.0
5.0
3.0
2.0
4.0
3.0
3.0
3.0
3.0
2.0
1.5
ERROR
1.0
3.0
3.0
3.0
2.0
5.0
3.0
3.0
1.5
2.0
1.0
4.0
1.5
3.0
1.0
4.0
1.5
3.0
4.0
3.0
3.0
3.0
3.0
2.0
3.0
1.5
4.0
3.0
4.0
3.0
1.5
3.0
3.0
1.5
4.0
4.0
2.0
4.0
1.0
5.0
4.0
5.0
4.0
4.0
4.0
3.0
2.0
1.0
1.5
2.0
3.0
4.0
5.0
2.0
3.0
4.0
1.5
4.0
4.0
4.0
5.0
2.0
1.5
5.0
5.0
3.0
5.0
4.0
4.0
4.0
1.0
4.0
1.0
1.0
4.0
4.0
1.0
5.0
4.0
3.0
3.0
5.0
4.0
4.0
4.0
1.0
1.5
1.0
4.0
4.0
3.0
5.0
4.0
3.0
3.0
4.0
1.0
4.0
1.0
4.0
5.0
3.0
2.0
4.0
3.0
5.0
4.0
4.0
1.0
1.0
4.0
1.5
ERROR
4.0
1.5
5.0
4.0
4.0
2.0
4.0
4.0
5.0
5.0
1.0
2.0
4.0
4.0
3.0
1.0
UNKNOWN
2.0
5.0
3.0
2.0
1.0
1.0
1.0
3.0
3.0
5.0
4.0
1.5
1.5
3.0
4.0
4.0
5.0
3.0
3.0
1.5
5.0
5.0
ERROR
3.0
2.0
5.0
1.0
3.0
5.0
ERROR
2.0
1.5
3.0
5.0
1.0
4.0
5.0
4.0
5.0
2.0
3.0
1.5
2.0
2.0
2.0
4.0
4.0
1.5
1.0
3.0
4.0
UNKNOWN
1.0
1.5
3.0
2.0
4.0
3.0
1.0
4.0
5.0
3.0
1.5
5.0
4.0
3.0
4.0
3.0
5.0
3.0
2.0
3.0
3.0
4.0
2.0
1.0
5.0
3.0
4.0
3.0
3.0
4.0
1.5
4.0
3.0
1.0
5.0
3.0
1.0
1.5
1.0
1.5
1.0
1.0
4.0
1.5
3.0
2.0
1.5
1.5
4.0
1.5
2.0
5.0
3.0
2.0
5.0
4.0
3.0
3.0
3.0
4.0
5.0
3.0
3.0
3.0
3.0
1.5
1.5
UNKNOWN
2.0
3.0
3.0
1.0
3.0
2.0
4.0
1.0
3.0
2.0
1.0
2.0
3.0
3.0
5.0
1.0
5.0
4.0
5.0
3.0
5.0
5.0
2.0
3.0
1.0
1.0
4.0
5.0
3.0
4.0
4.0
5.0
3.0
3.0
UNKNOWN
3.0
2.0
3.0
ERROR
2.0
3.0
4.0
ERROR
3.0
1.0
1.5
ERROR
3.0
4.0
5.0
1.5
4.0
3.0
3.0
1.5
5.0
2.0
1.5
4.0
3.0
1.0
ERROR
1.5
4.0
1.5
4.0
3.0
3.0
1.5
1.5
1.5
2.0
3.0
5.0
3.0
3.0
1.5
5.0
4.0
5.0
4.0
5.0
3.0
3.0
1.0
1.5
1.5
3.0
4.0
5.0
2.0
1.5
5.0
4.0
3.0
4.0
4.0
4.0
3.0
1.0
3.0
3.0
5.0
3.0
5.0
4.0
3.0
2.0
1.0
3.0
2.0
4.0
1.0
1.5
4.0
3.0
1.0
4.0
2.0
3.0
3.0
3.0
1.0
5.0
4.0
3.0
5.0
3.0
3.0
5.0
5.0
4.0
1.0
5.0
3.0
2.0
3.0
3.0
4.0
3.0
4.0
1.5
1.5
UNKNOWN
1.5
4.0
3.0
4.0
5.0
3.0
5.0
1.0
3.0
5.0
1.5
1.0
3.0
4.0
UNKNOWN
4.0
2.0
2.0
2.0
4.0
3.0
5.0
5.0
3.0
4.0
3.0
2.0
1.0
4.0
4.0
4.0
1.5
4.0
ERROR
3.0
1.0
2.0
1.5
3.0
UNKNOWN
2.0
3.0
4.0
3.0
3.0
1.0
4.0
5.0
1.5
UNKNOWN
4.0
3.0
1.5
1.5
4.0
3.0
2.0
1.0
4.0
1.0
5.0
5.0
2.0
5.0
3.0
4.0
3.0
4.0
3.0
4.0
2.0
1.0
4.0
3.0
2.0
1.0
ERROR
4.0
UNKNOWN
4.0
4.0
4.0
4.0
1.0
2.0
3.0
4.0
2.0
5.0
3.0
3.0
1.5
4.0
4.0
3.0
1.0
2.0
2.0
3.0
1.0
1.5
3.0
3.0
ERROR
ERROR
2.0
2.0
3.0
1.5
4.0
3.0
2.0
4.0
1.0
5.0
1.5
5.0
5.0
4.0
1.5
1.5
4.0
1.5
1.0
1.0
2.0
1.5
5.0
3.0
3.0
UNKNOWN
1.5
2.0
5.0
5.0
1.5
1.5
3.0
3.0
5.0
4.0
1.0
4.0
5.0
1.0
4.0
2.0
1.5
1.0
3.0
3.0
5.0
2.0
ERROR
4.0
1.5
UNKNOWN
5.0
1.0
3.0
2.0
4.0
2.0
3.0
4.0
4.0
3.0
4.0
1.5
1.5
3.0
5.0
3.0
3.0
3.0
1.0
1.5
3.0
2.0
4.0
1.0
2.0
1.5
5.0
5.0
4.0
4.0
2.0
2.0
5.0
1.5
3.0
4.0
3.0
2.0
3.0
2.0
5.0
1.5
3.0
5.0
4.0
3.0
4.0
5.0
3.0
2.0
2.0
3.0
5.0
1.0
1.5
2.0
3.0
2.0
ERROR
5.0
1.0
5.0
2.0
1.0
4.0
5.0
3.0
5.0
3.0
1.5
3.0
3.0
1.5
1.0
3.0
1.5
2.0
3.0
2.0
4.0
2.0
4.0
5.0
4.0
2.0
4.0
5.0
5.0
5.0
5.0
4.0
2.0
4.0
4.0
4.0
3.0
1.5
UNKNOWN
1.0
5.0
4.0
1.0
1.0
4.0
1.5
5.0
4.0
3.0
2.0
4.0
1.0
5.0
5.0
2.0
3.0
1.5
3.0
3.0
1.0
UNKNOWN
3.0
4.0
5.0
1.0
3.0
1.0
4.0
4.0
4.0
1.0
4.0
3.0
3.0
3.0
3.0
ERROR
2.0
3.0
3.0
3.0
1.5
3.0
1.0
UNKNOWN
1.5
1.5
1.5
2.0
5.0
4.0
1.5
5.0
5.0
3.0
1.5
1.5
1.5
4.0
1.0
4.0
3.0
3.0
2.0
1.0
5.0
3.0
3.0
4.0
1.0
4.0
5.0
3.0
2.0
3.0
5.0
2.0
2.0
4.0
4.0
2.0
3.0
4.0
3.0
5.0
5.0
2.0
4.0
UNKNOWN
5.0
1.5
3.0
2.0
4.0
UNKNOWN
3.0
3.0
2.0
4.0
1.0
3.0
2.0
1.0
3.0
2.0
4.0
5.0
4.0
3.0
1.0
4.0
4.0
3.0
1.0
1.5
5.0
1.0
2.0
2.0
5.0
1.0
1.5
4.0
5.0
3.0
1.5
1.0
1.0
1.0
ERROR
3.0
4.0
3.0
5.0
2.0
5.0
4.0
4.0
1.0
3.0
4.0
5.0
1.0
3.0
5.0
4.0
2.0
1.5
4.0
2.0
1.0
5.0
1.0
3.0
3.0
3.0
1.0
2.0
ERROR
1.5
3.0
2.0
5.0
4.0
4.0
ERROR
4.0
1.5
4.0
1.0
5.0
4.0
5.0
4.0
2.0
3.0
3.0
4.0
3.0
3.0
3.0
4.0
3.0
3.0
1.0
1.5
1.0
5.0
1.0
2.0
1.5
5.0
5.0
1.5
3.0
1.0
1.5
1.5
4.0
1.5
4.0
4.0
3.0
4.0
1.5
3.0
3.0
4.0
2.0
3.0
4.0
5.0
1.0
4.0
4.0
3.0
5.0
2.0
1.5
UNKNOWN
2.0
4.0
1.5
1.5
5.0
1.5
2.0
3.0
1.0
4.0
2.0
5.0
5.0
4.0
ERROR
4.0
4.0
1.5
4.0
3.0
3.0
1.5
3.0
UNKNOWN
4.0
3.0
1.5
4.0
5.0
5.0
2.0
3.0
4.0
3.0
2.0
3.0
2.0
2.0
3.0
3.0
3.0
1.0
1.5
1.5
5.0
5.0
1.5
3.0
1.0
3.0
5.0
4.0
4.0
4.0
5.0
1.0
3.0
3.0
3.0
1.5
1.5
1.0
4.0
1.5
1.0
2.0
4.0
3.0
3.0
4.0
1.5
3.0
1.0
1.5
5.0
2.0

4.0
5.0
3.0
1.0
4.0
3.0
4.0
5.0
2.0
5.0
3.0
3.0
4.0
3.0
5.0
4.0
3.0
3.0
4.0
UNKNOWN
1.0
5.0
4.0
ERROR
4.0
4.0
2.0
4.0
3.0
5.0
1.0
1.5
3.0
2.0
4.0
3.0
2.0
5.0
1.5
4.0
5.0
UNKNOWN
4.0
2.0
5.0
1.5
5.0
4.0
4.0
3.0
1.5
4.0
5.0
3.0
1.0
4.0
3.0
3.0
2.0
4.0
1.0
3.0
3.0
2.0
5.0
3.0
4.0
3.0
3.0
1.5
1.0
5.0
3.0
4.0
1.5
5.0
5.0
1.0
3.0
3.0
1.0
1.5
3.0
1.5
4.0
5.0
4.0
3.0
1.5
3.0
2.0
4.0
5.0
4.0
UNKNOWN
4.0
4.0
5.0
3.0
5.0
2.0
1.0
4.0
3.0
2.0
5.0
3.0
4.0
4.0
2.0
4.0
5.0
3.0
1.5
3.0
3.0
4.0
4.0
4.0
4.0
4.0

In [80]:
df2.head(70)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
65,TXN_7965998,Juice,1,UNKNOWN,3.0,Credit Card,In-store,2023-11-02
66,TXN_9238666,Cookie,1,UNKNOWN,1.0,ERROR,Takeaway,2023-07-31
67,TXN_1648671,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-05-21
68,TXN_4062737,Cake,3,3.0,9.0,Cash,In-store,2023-07-02
69,TXN_9249507,Cookie,4,1.0,4.0,Credit Card,In-store,2023-11-21

In [105]:
# for x in df.index:
#     df2.loc[x,"Quantity"]=int(df2.loc[x,"Quantity"])

# for x in df2.index:
#     print(df2.loc[x,"Quantity"])

# for x in df2.index:
#     if(df2.loc[x,"Total Spent"]=="ERROR" or df2.loc[x,"Total Spent"]=="UNKNOWN"):
#         df2.loc[x,"Total Spent"]= float(0.0)
    
#     else:
#         df2.loc[x,"Total Spent"]= float(df2.loc[x,"Total Spent"])

# for x in df2.index:
#     if(df2.loc[x,"Price Per Unit"]=="ERROR" or df2.loc[x,"Price Per Unit"]=="UNKNOWN"):
#         df2.loc[x,"Price Per Unit"]= float(0.0)
    
#     else:
#         df2.loc[x,"Price Per Unit"]= float(df2.loc[x,"Price Per Unit"])

In [140]:
# for x in df2.index:
#     print(type(df2.loc[x,"Quantity"]))

# df3 =df2
df2.head(70)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,0.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
65,TXN_7965998,Juice,1,0.0,3.0,Credit Card,In-store,2023-11-02
66,TXN_9238666,Cookie,1,0.0,1.0,ERROR,Takeaway,2023-07-31
67,TXN_1648671,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-05-21
68,TXN_4062737,Cake,3,3.0,9.0,Cash,In-store,2023-07-02
69,TXN_9249507,Cookie,4,1.0,4.0,Credit Card,In-store,2023-11-21

In [135]:
df3 = df3[(df3["Price Per Unit"] != 0.0) & (df2.loc[x,"Total Spent"]!=0.0)]

In [137]:
for x in df3.index:
    df3.loc[x,"Price Per Unit"] = df3.loc[x,"Total Spent"]/df3.loc[x,"Quantity"]

In [146]:
# df3.reset_index()
# df3

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,0.0,0.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
4247,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
4248,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
4249,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
4250,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
4251,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [154]:
df2 = df3

2.0
3.0
0.0
5.0
2.0
4.0
5.0
4.0
4.0
5.0
3.0
3.0
3.0
4.0
4.0
4.0
1.0
3.0
3.0
4.0
4.0
5.0
3.0
5.0
4.0
4.0
1.0
3.0
1.5
3.0
4.0
2.0
3.0
2.0
3.0
3.0
5.0
1.5
0.0
5.0
5.0
2.0
3.0
2.0
3.0
5.0
1.0
1.0
5.0
5.0
2.0
1.5
4.0
3.0
4.0
3.0
3.0
1.5
2.0
5.0
1.5
3.0
2.0
5.0
4.0
3.0
1.0
1.0
1.0
4.0
4.0
3.0
3.0
4.0
2.0
3.0
1.0
2.0
2.0
1.0
4.0
4.0
5.0
5.0
2.0
3.0
1.0
5.0
1.0
5.0
3.0
3.0
4.0
4.0
1.5
1.5
4.0
3.0
3.0
5.0
0.0
5.0
1.0
4.0
4.0
4.0
1.5
4.0
4.0
4.0
4.0
3.0
4.0
0.0
4.0
1.0
1.5
4.0
1.5
0.0
3.0
3.0
1.5
4.0
1.5
4.0
5.0
1.0
1.0
2.0
5.0
4.0
4.0
5.0
3.0
3.0
4.0
1.5
0.0
4.0
2.0
3.0
2.0
4.0
4.0
1.0
1.5
3.0
4.0
4.0
5.0
3.0
2.0
1.0
1.0
5.0
2.0
2.0
3.0
1.0
3.0
4.0
1.5
3.0
5.0
3.0
1.5
0.0
1.0
1.0
3.0
1.0
5.0
3.0
2.0
1.0
4.0
3.0
3.0
2.0
2.0
4.0
4.0
5.0
4.0
3.0
3.0
4.0
1.0
3.0
1.5
2.0
1.5
2.0
2.0
3.0
4.0
5.0
1.0
5.0
3.0
4.0
1.0
1.5
3.0
1.5
1.0
4.0
4.0
5.0
3.0
1.5
5.0
4.0
4.0
1.0
1.5
4.0
3.0
4.0
1.0
4.0
3.0
1.0
4.0
3.0
1.5
5.0
1.0
3.0
4.0
0.0
1.5
3.0
5.0
1.5
1.0
4.0
2.0
4.0
1.0
4.0
2.0
5.0
4.0
1.0
2.0
4.0
2.0
3.0
5.0
3.0
4.0
1.5
1.0
0.0
5.0
5.0
5.0
1.0
5.0
1.0
3.0
1.0
3.0
4.0
4.0
4.0
4.0
4.0
4.0
5.0
4.0
4.0
3.0
5.0
1.5
3.0
3.0
1.0
4.0
3.0
3.0
5.0
3.0
2.0
4.0
1.0
3.0
3.0
5.0
3.0
5.0
5.0
4.0
2.0
3.0
4.0
3.0
2.0
4.0
5.0
4.0
4.0
1.5
4.0
1.0
1.5
2.0
1.0
5.0
0.0
2.0
3.0
3.0
4.0
1.5
1.5
3.0
4.0
1.0
4.0
2.0
1.0
5.0
3.0
3.0
0.0
4.0
1.0
4.0
0.0
4.0
1.0
3.0
2.0
1.5
5.0
2.0
1.5
1.0
1.0
3.0
4.0
1.5
3.0
2.0
3.0
4.0
0.0
3.0
3.0
1.0
3.0
1.5
2.0
3.0
4.0
1.0
0.0
1.0
1.5
4.0
4.0
5.0
4.0
2.0
5.0
5.0
5.0
3.0
3.0
1.5
1.5
3.0
2.0
3.0
3.0
2.0
4.0
3.0
1.5
3.0
1.5
5.0
5.0
5.0
0.0
1.5
1.5
0.0
4.0
1.5
5.0
3.0
4.0
0.0
4.0
2.0
5.0
4.0
2.0
1.5
5.0
3.0
1.0
5.0
1.5
1.0
4.0
1.5
4.0
4.0
2.0
4.0
4.0
2.0
3.0
5.0
3.0
4.0
3.0
1.0
3.0
3.0
3.0
3.0
5.0
4.0
3.0
5.0
4.0
5.0
0.0
3.0
1.0
1.5
3.0
4.0
3.0
1.0
3.0
0.0
3.0
5.0
1.0
5.0
1.0
5.0
1.0
4.0
1.5
1.0
5.0
3.0
3.0
4.0
3.0
5.0
2.0
1.5
4.0
5.0
3.0
4.0
4.0
3.0
5.0
4.0
4.0
3.0
3.0
4.0
4.0
4.0
2.0
4.0
3.0
1.0
4.0
2.0
3.0
4.0
2.0
2.0
4.0
2.0
3.0
2.0
2.0
4.0
5.0
5.0
5.0
1.0
3.0
1.0
1.5
0.0
1.0
4.0
1.5
4.0
4.0
4.0
3.0
4.0
1.0
1.0
4.0
2.0
4.0
3.0
4.0
2.0
3.0
1.5
4.0
4.0
2.0
2.0
3.0
4.0
4.0
1.0
1.0
3.0
5.0
2.0
2.0
3.0
1.5
4.0
5.0
5.0
3.0
3.0
3.0
3.0
2.0
4.0
1.0
0.0
5.0
1.5
1.0
0.0
5.0
3.0
4.0
4.0
5.0
1.0
2.0
1.0
4.0
3.0
2.0
2.0
4.0
3.0
4.0
3.0
3.0
1.0
3.0
3.0
3.0
4.0
2.0
4.0
4.0
3.0
4.0
3.0
1.5
1.5
3.0
4.0
1.5
1.0
4.0
3.0
4.0
1.5
5.0
3.0
3.0
3.0
4.0
3.0
0.0
3.0
1.5
3.0
4.0
0.0
4.0
1.5
0.0
1.0
3.0
4.0
4.0
0.0
0.0
3.0
5.0
3.0
3.0
3.0
5.0
3.0
5.0
4.0
5.0
2.0
1.5
5.0
1.0
5.0
3.0
4.0
2.0
1.0
2.0
1.0
3.0
1.5
3.0
1.5
1.5
4.0
1.0
5.0
5.0
3.0
5.0
4.0
2.0
2.0
4.0
1.5
5.0
1.5
3.0
3.0
3.0
3.0
4.0
1.5
3.0
5.0
4.0
3.0
5.0
2.0
2.0
3.0
4.0
3.0
1.0
3.0
1.0
4.0
5.0
1.0
5.0
3.0
2.0
5.0
1.5
3.0
3.0
3.0
0.0
5.0
1.5
4.0
1.5
0.0
1.0
4.0
1.5
4.0
3.0
4.0
2.0
2.0
3.0
1.0
4.0
3.0
1.5
4.0
4.0
3.0
1.0
5.0
4.0
1.5
4.0
1.0
3.0
4.0
3.0
2.0
4.0
3.0
4.0
1.5
3.0
3.0
3.0
3.0
1.5
1.5
1.5
1.5
4.0
3.0
0.0
3.0
1.0
3.0
2.0
3.0
2.0
5.0
4.0
0.0
1.0
5.0
3.0
4.0
1.5
4.0
3.0
2.0
4.0
4.0
2.0
4.0
3.0
0.0
2.0
5.0
1.0
4.0
1.0
1.0
4.0
2.0
1.5
1.5
3.0
3.0
5.0
1.0
3.0
3.0
4.0
1.0
0.0
1.0
3.0
2.0
4.0
3.0
4.0
1.0
4.0
5.0
4.0
3.0
4.0
4.0
1.5
4.0
1.5
4.0
1.5
2.0
3.0
1.5
3.0
5.0
3.0
5.0
1.0
3.0
2.0
1.5
4.0
5.0
5.0
3.0
4.0
4.0
1.0
3.0
3.0
1.5
2.0
2.0
3.0
0.0
3.0
0.0
1.5
1.5
4.0
4.0
1.5
3.0
3.0
2.0
4.0
2.0
5.0
5.0
1.0
3.0
4.0
2.0
4.0
3.0
4.0
4.0
5.0
3.0
1.0
4.0
0.0
3.0
4.0
3.0
1.0
1.0
3.0
5.0
1.5
2.0
2.0
4.0
3.0
4.0
4.0
0.0
1.5
3.0
3.0
2.0
4.0
3.0
4.0
4.0
4.0
5.0
1.5
3.0
4.0
2.0
3.0
5.0
2.0
2.0
5.0
1.5
3.0
4.0
3.0
2.0
2.0
5.0
4.0
4.0
5.0
5.0
4.0
2.0
3.0
4.0
5.0
1.5
0.0
3.0
2.0
3.0
4.0
4.0
4.0
4.0
2.0
5.0
3.0
4.0
1.5
3.0
3.0
5.0
5.0
1.5
1.5
3.0
2.0
1.0
5.0
3.0
2.0
3.0
5.0
1.0
3.0
1.0
5.0
5.0
4.0
4.0
4.0
2.0
3.0
3.0
4.0
1.0
4.0
4.0
1.5
3.0
5.0
4.0
5.0
5.0
3.0
2.0
4.0
4.0
2.0
2.0
3.0
4.0
1.0
1.5
4.0
3.0
1.0
4.0
2.0
5.0
1.5
5.0
3.0
4.0
4.0
3.0
2.0
1.5
1.5
2.0
2.0
5.0
4.0
1.5
4.0
2.0
1.0
4.0
1.0
4.0
1.0
4.0
1.5
1.5
2.0
5.0
4.0
4.0
1.5
4.0
2.0
3.0
3.0
1.5
1.5
4.0
5.0
3.0
2.0
1.0
1.0
2.0
2.0
1.0
0.0
4.0
2.0
5.0
0.0
4.0
5.0
0.0
3.0
1.5
2.0
4.0
4.0
3.0
1.5
1.0
3.0
1.0
1.5
4.0
2.0
1.0
5.0
3.0
3.0
3.0
1.0
4.0
4.0
2.0
2.0
1.5
4.0
5.0
5.0
2.0
3.0
4.0
4.0
3.0
3.0
5.0
0.0
1.5
3.0
3.0
1.0
1.0
4.0
1.5
1.5
2.0
1.0
1.0
3.0
5.0
3.0
0.0
3.0
4.0
3.0
1.0
1.0
3.0
3.0
1.0
3.0
1.5
2.0
2.0
2.0
4.0
2.0
4.0
4.0
3.0
1.0
4.0
3.0
2.0
1.0
3.0
3.0
3.0
3.0
1.5
5.0
5.0
1.0
3.0
2.0
1.5
3.0
3.0
5.0
4.0
4.0
2.0
3.0
1.0
3.0
2.0
3.0
3.0
4.0
2.0
1.0
5.0
4.0
2.0
3.0
3.0
4.0
3.0
4.0
4.0
1.0
4.0
3.0
4.0
0.0
3.0
3.0
3.0
3.0
0.0
1.0
2.0
1.0
1.0
5.0
4.0
4.0
5.0
1.5
1.0
1.5
5.0
3.0
1.5
3.0
3.0
1.0
3.0
4.0
5.0
3.0
2.0
3.0
4.0
1.5
1.5
4.0
4.0
3.0
2.0
3.0
4.0
4.0
1.0
0.0
2.0
4.0
5.0
4.0
5.0
4.0
1.5
1.5
4.0
4.0
5.0
4.0
4.0
3.0
2.0
1.5
5.0
2.0
2.0
3.0
3.0
1.0
1.0
3.0
5.0
5.0
4.0
2.0
1.5
1.5
3.0
3.0
4.0
5.0
4.0
3.0
1.5
3.0
3.0
5.0
3.0
1.5
4.0
3.0
3.0
1.5
3.0
1.5
1.0
3.0
4.0
2.0
1.0
4.0
1.0
4.0
2.0
4.0
4.0
5.0
3.0
4.0
0.0
1.5
3.0
3.0
5.0
5.0
5.0
0.0
1.0
3.0
3.0
5.0
2.0
5.0
3.0
3.0
3.0
4.0
5.0
1.0
4.0
3.0
3.0
3.0
2.0
4.0
4.0
3.0
3.0
1.5
3.0
4.0
1.0
1.0
3.0
4.0
1.5
5.0
3.0
4.0
1.5
5.0
3.0
3.0
1.5
2.0
3.0
1.5
4.0
3.0
3.0
0.0
0.0
1.0
4.0
3.0
3.0
4.0
3.0
2.0
1.5
1.5
5.0
4.0
4.0
4.0
3.0
3.0
3.0
3.0
1.0
3.0
3.0
3.0
1.0
2.0
1.5
3.0
2.0
4.0
4.0
3.0
3.0
3.0
3.0
5.0
1.0
1.0
4.0
4.0
5.0
1.0
5.0
4.0
5.0
5.0
5.0
0.0
3.0
4.0
3.0
3.0
1.0
4.0
2.0
0.0
4.0
3.0
5.0
2.0
3.0
5.0
3.0
1.5
4.0
3.0
3.0
4.0
1.0
1.0
1.0
1.0
3.0
1.0
4.0
4.0
4.0
3.0
3.0
3.0
5.0
5.0
4.0
4.0
1.5
5.0
1.5
1.5
3.0
1.5
3.0
4.0
3.0
1.5
4.0
4.0
3.0
1.0
3.0
1.0
4.0
3.0
3.0
5.0
4.0
3.0
4.0
3.0
1.0
4.0
1.0
1.0
4.0
4.0
3.0
0.0
3.0
2.0
3.0
4.0
2.0
4.0
3.0
4.0
4.0
4.0
3.0
1.5
4.0
3.0
3.0
3.0
1.5
1.5
4.0
2.0
1.5
3.0
2.0
5.0
4.0
1.5
2.0
1.5
1.0
4.0
2.0
2.0
0.0
3.0
5.0
1.0
1.0
1.5
4.0
5.0
3.0
4.0
3.0
3.0
2.0
1.5
0.0
3.0
4.0
3.0
4.0
5.0
5.0
1.5
3.0
4.0
0.0
4.0
3.0
2.0
4.0
3.0
1.5
1.0
5.0
5.0
0.0
1.5
3.0
1.0
3.0
1.0
3.0
4.0
3.0
2.0
1.0
3.0
3.0
1.0
4.0
1.5
3.0
4.0
1.5
4.0
5.0
5.0
3.0
4.0
1.0
3.0
5.0
4.0
2.0
4.0
2.0
3.0
1.5
5.0
1.5
1.5
5.0
1.5
5.0
4.0
2.0
5.0
1.0
3.0
4.0
1.0
5.0
3.0
3.0
3.0
2.0
2.0
3.0
0.0
4.0
2.0
2.0
4.0
1.5
0.0
3.0
1.5
4.0
1.5
1.5
1.5
5.0
1.5
4.0
4.0
4.0
4.0
3.0
1.0
1.0
3.0
5.0
1.5
1.0
1.5
1.5
1.0
4.0
2.0
1.0
5.0
4.0
2.0
1.5
1.5
5.0
1.5
4.0
4.0
2.0
1.0
1.0
4.0
4.0
1.5
5.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
5.0
4.0
4.0
1.0
4.0
4.0
1.5
1.5
1.5
3.0
0.0
2.0
3.0
1.0
2.0
5.0
3.0
5.0
4.0
1.0
4.0
1.0
1.0
2.0
4.0
3.0
4.0
2.0
1.0
3.0
1.0
4.0
3.0
1.0
5.0
1.0
3.0
4.0
2.0
4.0
1.5
2.0
3.0
3.0
3.0
1.0
3.0
3.0
3.0
2.0
1.0
2.0
1.5
2.0
1.0
3.0
1.0
4.0
3.0
2.0
3.0
4.0
1.0
2.0
5.0
4.0
3.0
5.0
2.0
3.0
5.0
3.0
5.0
2.0
3.0
3.0
5.0
1.0
1.5
2.0
1.0
1.5
4.0
3.0
3.0
1.0
3.0
5.0
1.0
1.0
3.0
5.0
4.0
1.0
3.0
1.5
1.0
3.0
2.0
4.0
3.0
5.0
3.0
4.0
2.0
3.0
1.5
1.0
1.0
1.0
3.0
3.0
5.0
1.5
2.0
4.0
5.0
3.0
1.0
2.0
5.0
2.0
5.0
2.0
1.0
1.5
5.0
1.5
1.0
0.0
3.0
3.0
3.0
0.0
4.0
4.0
1.5
3.0
0.0
2.0
2.0
3.0
1.0
2.0
1.5
1.5
4.0
2.0
4.0
1.5
4.0
4.0
1.0
4.0
3.0
5.0
2.0
5.0
1.5
4.0
3.0
3.0
4.0
3.0
4.0
1.0
3.0
5.0
1.0
2.0
3.0
5.0
3.0
4.0
3.0
3.0
1.0
4.0
1.0
3.0
5.0
5.0
3.0
5.0
3.0
4.0
3.0
1.5
4.0
2.0
3.0
1.0
3.0
4.0
3.0
1.5
3.0
1.0
2.0
3.0
1.5
4.0
4.0
1.0
3.0
3.0
5.0
4.0
3.0
1.5
4.0
3.0
1.0
5.0
3.0
1.0
1.0
4.0
1.0
4.0
1.5
1.0
2.0
1.5
4.0
5.0
5.0
4.0
5.0
3.0
3.0
1.0
3.0
2.0
2.0
5.0
4.0
3.0
1.5
1.0
3.0
4.0
2.0
4.0
4.0
3.0
1.0
4.0
1.5
4.0
1.0
2.0
0.0
5.0
4.0
4.0
1.0
5.0
3.0
1.5
4.0
1.0
5.0
5.0
2.0
4.0
4.0
1.0
3.0
3.0
3.0
3.0
3.0
1.0
1.5
1.0
2.0
3.0
4.0
1.0
4.0
4.0
3.0
3.0
4.0
4.0
3.0
4.0
3.0
0.0
2.0
1.5
3.0
3.0
1.5
4.0
2.0
3.0
1.0
4.0
5.0
3.0
4.0
5.0
3.0
3.0
4.0
1.5
3.0
2.0
4.0
1.5
4.0
0.0
3.0
1.5
3.0
1.0
1.5
2.0
2.0
4.0
4.0
1.0
2.0
4.0
1.5
0.0
4.0
5.0
4.0
4.0
1.0
1.5
4.0
1.5
3.0
4.0
4.0
3.0
4.0
4.0
3.0
1.5
4.0
1.0
1.5
5.0
4.0
3.0
3.0
4.0
3.0
4.0
1.0
0.0
4.0
4.0
5.0
0.0
1.5
5.0
2.0
4.0
3.0
3.0
4.0
1.0
2.0
4.0
3.0
4.0
4.0
5.0
4.0
4.0
2.0
1.5
5.0
1.5
5.0
1.0
5.0
1.5
4.0
4.0
1.5
5.0
4.0
1.0
0.0
3.0
3.0
4.0
3.0
1.5
1.5
1.5
4.0
3.0
1.0
3.0
0.0
4.0
3.0
1.0
1.0
4.0
3.0
4.0
3.0
2.0
2.0
3.0
3.0
1.5
4.0
1.0
3.0
1.0
3.0
5.0
3.0
3.0
5.0
5.0
1.5
0.0
1.5
5.0
4.0
3.0
4.0
4.0
5.0
3.0
4.0
5.0
4.0
4.0
1.5
1.0
4.0
0.0
4.0
4.0
0.0
3.0
3.0
5.0
4.0
3.0
1.5
2.0
4.0
2.0
1.5
2.0
1.5
2.0
3.0
4.0
1.5
4.0
3.0
4.0
2.0
2.0
5.0
2.0
4.0
3.0
4.0
1.5
5.0
3.0
3.0
4.0
1.0
1.5
1.0
2.0
3.0
3.0
1.0
3.0
1.0
3.0
5.0
3.0
4.0
2.0
3.0
3.0
2.0
3.0
5.0
1.5
4.0
3.0
2.0
1.5
5.0
2.0
4.0
0.0
3.0
4.0
3.0
1.0
2.0
4.0
5.0
4.0
3.0
2.0
5.0
1.0
4.0
1.5
2.0
4.0
1.0
5.0
1.0
4.0
4.0
5.0
2.0
4.0
5.0
5.0
4.0
1.0
3.0
1.5
3.0
3.0
0.0
4.0
4.0
1.5
4.0
3.0
3.0
1.5
3.0
2.0
5.0
5.0
5.0
5.0
1.0
3.0
3.0
4.0
3.0
5.0
3.0
1.0
5.0
2.0
4.0
3.0
1.5
4.0
4.0
3.0
1.0
4.0
1.5
0.0
1.0
0.0
3.0
3.0
1.5
4.0
4.0
3.0
5.0
3.0
3.0
3.0
3.0
3.0
3.0
2.0
2.0
4.0
4.0
0.0
5.0
5.0
5.0
1.0
3.0
3.0
0.0
1.0
4.0
2.0
4.0
1.0
3.0
2.0
1.5
5.0
5.0
1.0
1.5
4.0
1.0
1.0
3.0
4.0
4.0
4.0
1.5
2.0
1.0
1.0
2.0
5.0
5.0
1.5
0.0
4.0
3.0
4.0
2.0
0.0
4.0
2.0
4.0
3.0
3.0
1.0
1.0
2.0
5.0
3.0
4.0
3.0
1.0
1.5
4.0
1.5
3.0
3.0
4.0
3.0
2.0
2.0
2.0
2.0
4.0
2.0
2.0
3.0
1.5
4.0
1.0
1.5
4.0
1.5
4.0
3.0
1.0
4.0
1.5
2.0
4.0
3.0
2.0
4.0
4.0
3.0
3.0
3.0
2.0
1.0
0.0
1.0
2.0
2.0
1.5
1.0
1.5
1.5
1.5
4.0
4.0
4.0
2.0
5.0
5.0
5.0
2.0
3.0
5.0
3.0
2.0
1.5
5.0
4.0
3.0
4.0
4.0
1.5
2.0
1.5
1.5
1.0
1.0
4.0
4.0
5.0
0.0
4.0
5.0
1.0
5.0
4.0
4.0
3.0
4.0
4.0
2.0
3.0
2.0
4.0
3.0
5.0
5.0
4.0
4.0
4.0
3.0
2.0
3.0
3.0
1.5
3.0
0.0
4.0
2.0
2.0
1.5
3.0
1.0
5.0
2.0
4.0
1.0
3.0
2.0
4.0
1.0
1.0
1.0
1.0
5.0
5.0
3.0
3.0
1.5
4.0
5.0
1.0
3.0
1.5
4.0
5.0
2.0
1.0
0.0
4.0
4.0
1.0
2.0
2.0
1.0
3.0
4.0
1.5
0.0
1.5
4.0
5.0
4.0
1.0
1.0
3.0
1.0
3.0
3.0
4.0
2.0
1.0
1.5
5.0
3.0
3.0
1.0
4.0
2.0
3.0
1.0
2.0
3.0
3.0
4.0
4.0
4.0
1.0
1.5
5.0
4.0
3.0
4.0
3.0
3.0
3.0
3.0
0.0
1.0
2.0
5.0
0.0
5.0
1.0
3.0
5.0
3.0
4.0
3.0
4.0
0.0
1.5
4.0
4.0
3.0
1.0
3.0
2.0
1.0
1.5
1.5
5.0
5.0
2.0
4.0
3.0
1.0
3.0
5.0
3.0
1.5
1.0
4.0
3.0
3.0
1.5
1.0
1.5
1.0
1.0
5.0
2.0
4.0
1.5
1.0
0.0
3.0
3.0
1.5
3.0
1.0
4.0
4.0
3.0
1.5
1.5
4.0
1.5
1.5
1.5
3.0
5.0
3.0
2.0
2.0
2.0
5.0
4.0
4.0
4.0
3.0
5.0
1.0
3.0
4.0
5.0
1.5
1.0
5.0
3.0
3.0
4.0
1.5
1.5
1.0
5.0
3.0
3.0
5.0
3.0
3.0
4.0
2.0
3.0
5.0
5.0
2.0
5.0
4.0
3.0
3.0
1.0
3.0
2.0
4.0
3.0
1.0
2.0
1.0
1.0
3.0
1.5
1.0
4.0
5.0
3.0
4.0
1.0
1.5
3.0
2.0
1.0
1.0
2.0
5.0
5.0
3.0
3.0
5.0
3.0
3.0
3.0
2.0
4.0
1.5
3.0
2.0
4.0
1.0
1.0
3.0
5.0
3.0
3.0
3.0
3.0
4.0
0.0
1.0
3.0
1.5
2.0
1.5
4.0
3.0
1.5
4.0
2.0
3.0
1.5
2.0
4.0
4.0
3.0
5.0
4.0
1.0
3.0
5.0
3.0
3.0
1.0
3.0
2.0
1.0
5.0
3.0
4.0
4.0
3.0
5.0
3.0
2.0
4.0
3.0
1.0
3.0
3.0
3.0
4.0
1.0
3.0
4.0
4.0
1.0
1.0
2.0
5.0
2.0
3.0
4.0
1.0
0.0
4.0
3.0
3.0
3.0
3.0
5.0
3.0
4.0
0.0
1.5
3.0
1.5
1.0
1.5
5.0
1.0
1.0
0.0
3.0
2.0
4.0
3.0
4.0
3.0
3.0
2.0
2.0
1.5
2.0
1.0
2.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
3.0
3.0
3.0
1.0
1.0
2.0
4.0
3.0
4.0
3.0
3.0
4.0
4.0
1.5
1.5
4.0
4.0
3.0
3.0
4.0
1.0
4.0
4.0
1.5
1.5
3.0
1.5
5.0
4.0
1.5
3.0
4.0
1.0
3.0
1.5
1.0
1.0
3.0
5.0
1.0
2.0
4.0
1.0
4.0
5.0
3.0
1.0
1.0
4.0
4.0
3.0
1.5
4.0
1.5
1.5
2.0
4.0
4.0
2.0
3.0
1.0
5.0
4.0
4.0
2.0
0.0
1.5
5.0
1.5
4.0
0.0
2.0
3.0
5.0
5.0
1.0
3.0
4.0
3.0
4.0
4.0
0.0
4.0
2.0
4.0
1.0
2.0
2.0
4.0
1.5
1.0
5.0
1.5
2.0
4.0
2.0
3.0
2.0
3.0
3.0
3.0
1.5
5.0
4.0
1.5
1.0
3.0
1.5
4.0
3.0
3.0
1.5
4.0
5.0
3.0
3.0
2.0
4.0
3.0
1.5
2.0
1.5
3.0
3.0
4.0
5.0
1.5
4.0
4.0
1.0
4.0
3.0
1.5
3.0
3.0
3.0
2.0
3.0
2.0
3.0
4.0
3.0
4.0
1.0
1.5
1.5
2.0
4.0
5.0
2.0
1.5
4.0
3.0
0.0
5.0
3.0
3.0
5.0
2.0
4.0
4.0
1.0
2.0
1.0
4.0
4.0
3.0
4.0
2.0
4.0
1.0
2.0
5.0
4.0
1.0
3.0
4.0
3.0
1.0
2.0
0.0
3.0
2.0
0.0
1.0
2.0
5.0
3.0
3.0
3.0
4.0
5.0
1.0
4.0
1.5
1.5
4.0
5.0
3.0
3.0
2.0
5.0
4.0
3.0
1.0
2.0
5.0
4.0
4.0
4.0
4.0
2.0
4.0
4.0
3.0
3.0
4.0
1.0
3.0
1.0
4.0
1.5
0.0
3.0
1.5
1.0
4.0
5.0
5.0
3.0
4.0
2.0
3.0
3.0
4.0
3.0
3.0
4.0
4.0
2.0
1.0
3.0
1.5
3.0
0.0
1.5
4.0
1.5
4.0
5.0
1.0
3.0
1.5
3.0
4.0
1.0
2.0
5.0
3.0
4.0
5.0
4.0
3.0
3.0
3.0
4.0
4.0
1.0
4.0
4.0
5.0
3.0
2.0
3.0
4.0
3.0
2.0
3.0
3.0
5.0
3.0
1.0
1.0
2.0
4.0
3.0
1.5
1.0
1.0
3.0
4.0
4.0
4.0
1.0
1.5
3.0
4.0
1.5
2.0
5.0
3.0
5.0
2.0
1.0
5.0
1.5
5.0
1.0
3.0
4.0
1.0
2.0
3.0
3.0
3.0
1.5
2.0
3.0
2.0
1.5
3.0
1.0
3.0
3.0
2.0
3.0
5.0
5.0
4.0
3.0
3.0
0.0
1.5
4.0
3.0
4.0
3.0
2.0
1.0
4.0
4.0
1.5
3.0
4.0
1.0
2.0
3.0
3.0
3.0
5.0
3.0
5.0
3.0
1.5
5.0
0.0
4.0
1.0
3.0
4.0
2.0
3.0
0.0
1.5
5.0
4.0
3.0
0.0
3.0
4.0
1.0
1.0
3.0
2.0
2.0
3.0
1.5
5.0
4.0
3.0
5.0
5.0
4.0
4.0
4.0
4.0
3.0
1.0
2.0
3.0
4.0
3.0
1.5
1.5
1.5
3.0
0.0
5.0
1.5
5.0
1.0
1.0
1.5
1.5
4.0
3.0
1.5
5.0
1.0
4.0
1.0
4.0
4.0
5.0
3.0
1.5
1.0
0.0
4.0
3.0
4.0
1.5
3.0
4.0
4.0
3.0
1.5
2.0
5.0
3.0
2.0
4.0
3.0
3.0
3.0
3.0
2.0
1.5
1.0
3.0
3.0
3.0
2.0
5.0
3.0
3.0
1.5
2.0
1.0
4.0
1.5
3.0
1.0
4.0
1.5
3.0
4.0
3.0
3.0
3.0
3.0
2.0
3.0
1.5
4.0
3.0
4.0
3.0
1.5
3.0
3.0
1.5
4.0
4.0
2.0
4.0
1.0
5.0
4.0
5.0
4.0
4.0
4.0
3.0
0.0
1.0
1.5
2.0
3.0
4.0
5.0
2.0
3.0
4.0
1.5
4.0
4.0
4.0
5.0
2.0
1.5
5.0
5.0
3.0
5.0
4.0
4.0
0.0
1.0
4.0
1.0
1.0
4.0
4.0
1.0
5.0
4.0
3.0
3.0
5.0
4.0
4.0
4.0
1.0
1.5
1.0
4.0
0.0
3.0
5.0
4.0
3.0
3.0
4.0
1.0
4.0
1.0
4.0
5.0
3.0
2.0
4.0
3.0
5.0
4.0
4.0
1.0
1.0
4.0
1.5
4.0
1.5
5.0
4.0
4.0
2.0
4.0
4.0
5.0
5.0
1.0
2.0
4.0
4.0
3.0
1.0
2.0
5.0
3.0
2.0
1.0
1.0
1.0
3.0
3.0
5.0
4.0
1.5
1.5
3.0
4.0
4.0
5.0
3.0
3.0
1.5
5.0
5.0
3.0
2.0
5.0
1.0
3.0
5.0
2.0
1.5
3.0
5.0
1.0
4.0
5.0
4.0
5.0
2.0
3.0
1.5
2.0
2.0
2.0
4.0
4.0
1.5
1.0
3.0
4.0
1.0
1.5
3.0
2.0
4.0
3.0
1.0
4.0
5.0
3.0
1.5
5.0
4.0
3.0
4.0
3.0
5.0
3.0
2.0
3.0
3.0
4.0
2.0
1.0
5.0
3.0
4.0
3.0
3.0
4.0
1.5
4.0
3.0
1.0
5.0
3.0
1.0
1.5
1.0
1.5
1.0
1.0
4.0
1.5
3.0
2.0
1.5
1.5
4.0
1.5
2.0
5.0
3.0
2.0
5.0
4.0
3.0
3.0
3.0
4.0
5.0
3.0
3.0
3.0
3.0
1.5
1.5
2.0
3.0
3.0
1.0
3.0
2.0
4.0
1.0
3.0
2.0
1.0
2.0
3.0
3.0
5.0
1.0
5.0
4.0
5.0
3.0
5.0
5.0
2.0
3.0
1.0
1.0
4.0
5.0
3.0
4.0
4.0
5.0
3.0
3.0
3.0
2.0
3.0
2.0
3.0
4.0
3.0
1.0
1.5
3.0
4.0
5.0
1.5
4.0
3.0
3.0
1.5
5.0
2.0
1.5
4.0
3.0
1.0
1.5
4.0
1.5
4.0
3.0
3.0
1.5
1.5
1.5
2.0
3.0
5.0
3.0
3.0
1.5
5.0
4.0
5.0
4.0
5.0
3.0
3.0
1.0
1.5
1.5
3.0
4.0
5.0
2.0
1.5
5.0
4.0
3.0
4.0
4.0
4.0
3.0
1.0
3.0
3.0
5.0
3.0
5.0
4.0
3.0
2.0
1.0
3.0
2.0
4.0
1.0
1.5
4.0
3.0
1.0
4.0
2.0
3.0
3.0
3.0
1.0
5.0
4.0
3.0
5.0
3.0
3.0
5.0
5.0
4.0
1.0
0.0
3.0
0.0
3.0
3.0
4.0
3.0
4.0
1.5
1.5
1.5
4.0
3.0
4.0
5.0
3.0
5.0
1.0
3.0
5.0
1.5
1.0
0.0
4.0
4.0
2.0
2.0
2.0
4.0
3.0
5.0
5.0
3.0
4.0
3.0
2.0
1.0
4.0
4.0
4.0
1.5
4.0
3.0
1.0
2.0
1.5
3.0
2.0
3.0
4.0
3.0
3.0
1.0
4.0
5.0
1.5
0.0
3.0
1.5
1.5
4.0
3.0
2.0
1.0
4.0
1.0
5.0
5.0
2.0
5.0
3.0
4.0
3.0
4.0
3.0
4.0
2.0
1.0
4.0
0.0
2.0
1.0
4.0
4.0
4.0
4.0
4.0
1.0
2.0
3.0
0.0
2.0
5.0
3.0
3.0
1.5
4.0
4.0
3.0
1.0
2.0
2.0
3.0
1.0
1.5
3.0
3.0
2.0
2.0
3.0
1.5
4.0
3.0
2.0
4.0
1.0
5.0
1.5
5.0
5.0
4.0
1.5
1.5
4.0
1.5
1.0
1.0
2.0
1.5
5.0
3.0
3.0
1.5
2.0
5.0
5.0
1.5
1.5
3.0
3.0
5.0
4.0
1.0
4.0
5.0
1.0
4.0
2.0
1.5
1.0
3.0
3.0
5.0
2.0
4.0
1.5
5.0
0.0
3.0
2.0
4.0
2.0
3.0
4.0
4.0
3.0
4.0
1.5
1.5
3.0
5.0
3.0
3.0
3.0
1.0
1.5
3.0
2.0
4.0
1.0
2.0
1.5
5.0
5.0
4.0
4.0
2.0
2.0
5.0
1.5
3.0
4.0
0.0
2.0
3.0
2.0
5.0
1.5
3.0
5.0
4.0
3.0
4.0
5.0
3.0
2.0
2.0
3.0
5.0
1.0
1.5
2.0
3.0
2.0
5.0
1.0
5.0
2.0
1.0
4.0
5.0
3.0
5.0
3.0
1.5
3.0
3.0
1.5
1.0
3.0
1.5
2.0
3.0
2.0
4.0
2.0
4.0
5.0
4.0
2.0
4.0
5.0
5.0
5.0
5.0
4.0
2.0
4.0
4.0
4.0
3.0
1.5
1.0
5.0
0.0
1.0
1.0
4.0
1.5
5.0
4.0
3.0
2.0
4.0
1.0
5.0
0.0
2.0
3.0
1.5
3.0
3.0
1.0
3.0
4.0
5.0
1.0
3.0
1.0
4.0
4.0
4.0
0.0
4.0
3.0
3.0
3.0
3.0
2.0
3.0
0.0
3.0
1.5
3.0
1.0
1.5
1.5
1.5
2.0
5.0
4.0
1.5
5.0
5.0
3.0
1.5
1.5
1.5
4.0
1.0
4.0
3.0
3.0
2.0
1.0
5.0
3.0
3.0
4.0
1.0
4.0
5.0
3.0
2.0
3.0
5.0
2.0
2.0
4.0
4.0
2.0
3.0
4.0
3.0
5.0
5.0
2.0
4.0
5.0
1.5
0.0
2.0
4.0
3.0
3.0
2.0
4.0
1.0
3.0
2.0
1.0
3.0
2.0
4.0
5.0
4.0
3.0
1.0
4.0
4.0
3.0
1.0
1.5
5.0
1.0
2.0
2.0
5.0
1.0
1.5
4.0
5.0
3.0
1.5
1.0
1.0
1.0
3.0
4.0
3.0
5.0
2.0
5.0
4.0
4.0
1.0
3.0
4.0
5.0
1.0
3.0
5.0
4.0
2.0
1.5
4.0
0.0
1.0
5.0
1.0
3.0
3.0
3.0
1.0
2.0
1.5
3.0
2.0
5.0
4.0
4.0
4.0
1.5
4.0
1.0
5.0
4.0
5.0
4.0
2.0
3.0
3.0
4.0
3.0
3.0
3.0
4.0
3.0
3.0
1.0
1.5
1.0
5.0
1.0
2.0
1.5
5.0
5.0
1.5
3.0
1.0
1.5
1.5
4.0
1.5
4.0
4.0
3.0
4.0
1.5
3.0
3.0
4.0
2.0
3.0
4.0
5.0
1.0
4.0
4.0
3.0
5.0
2.0
1.5
2.0
4.0
1.5
1.5
5.0
1.5
2.0
3.0
1.0
4.0
2.0
5.0
5.0
4.0
4.0
4.0
1.5
4.0
3.0
3.0
1.5
3.0
4.0
3.0
1.5
4.0
5.0
5.0
2.0
3.0
0.0
3.0
2.0
3.0
2.0
2.0
3.0
3.0
3.0
0.0
1.5
1.5
5.0
5.0
0.0
3.0
0.0
3.0
5.0
4.0
4.0
4.0
5.0
1.0
3.0
3.0
3.0
1.5
1.5
1.0
4.0
1.5
1.0
2.0
4.0
3.0
3.0
4.0
0.0
3.0
1.0
1.5
5.0
0.0
4.0
5.0
3.0
1.0
0.0
3.0
4.0
5.0
2.0
5.0
3.0
3.0
4.0
3.0
5.0
4.0
3.0
3.0
4.0
1.0
5.0
4.0
4.0
4.0
2.0
4.0
3.0
5.0
1.0
1.5
3.0
0.0
4.0
3.0
2.0
5.0
1.5
4.0
5.0
4.0
2.0
5.0
1.5
5.0
4.0
4.0
3.0
1.5
4.0
5.0
3.0
1.0
4.0
3.0
3.0
2.0
4.0
1.0
3.0
0.0
2.0
5.0
3.0
4.0
3.0
3.0
1.5
1.0
5.0
3.0
4.0
1.5
5.0
5.0
1.0
3.0
3.0
1.0
1.5
3.0
1.5
4.0
5.0
4.0
3.0
1.5
3.0
2.0
4.0
5.0
4.0
4.0
4.0
5.0
3.0
5.0
2.0
1.0
4.0
3.0
0.0
5.0
3.0
4.0
4.0
2.0
4.0
5.0
3.0
1.5
3.0
0.0
4.0
4.0
4.0
4.0
4.0

In [169]:
# for x in df2.index:
#     df2.loc[x,"Payment Method"]=str(df2.loc[x,"Payment Method"])

for x in df2.index:
    if df2.loc[x,"Payment Method"]== "UNKNOWN" or df2.loc[x,"Payment Method"]== "ERROR":
        df2.loc[x,"Payment Method"]="Cash"

In [183]:
df2["Payment Method"].value_counts().get("ERROR",0)

0

In [189]:
# for x in df2.index:
#     if(df2.loc[x,"Price Per Unit"]==0.0 and df2.loc[x,"Total Spent"]==0.0 ):
#         df2.loc[x,"Payment Method"] = "NILL"

In [190]:
df3=  df2.copy()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,0.0,0.0,NILL,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Cash,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
4247,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
4248,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
4249,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
4250,TXN_2739140,Smoothie,4,4.0,16.0,Cash,In-store,2023-07-05
4251,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [203]:
# df2["Location"]=df2["Location"].replace("UNKNOWN","In-store") # default
# df2["Location"]=df2["Location"].replace("ERROR","In-store") # default

In [204]:
df2.to_excel("cleaned_data.xlsx", index=False)

In [205]:
temp = df2.copy()

In [210]:
df2 = df2[df2["Transaction Date"] != "ERROR"]

In [211]:
df2 = df2[df2["Transaction Date"] != "UNKNOWN"]

In [212]:
df2.to_excel("cleaned_data.xlsx", index=False)

In [218]:
df2.reset_index(inplace = True)

In [219]:
df2

,index,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,2,TXN_4271903,Cookie,4,0.0,0.0,NILL,In-store,2023-07-19
3,3,TXN_7034554,Salad,2,5.0,10.0,Cash,In-store,2023-04-27
4,4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...,...
3969,4247,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
3970,4248,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
3971,4249,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
3972,4250,TXN_2739140,Smoothie,4,4.0,16.0,Cash,In-store,2023-07-05
3973,4251,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [221]:
df2.drop(columns = "index",inplace = True)

In [222]:
df2

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,0.0,0.0,NILL,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Cash,In-store,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
3969,TXN_9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
3970,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
3971,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
3972,TXN_2739140,Smoothie,4,4.0,16.0,Cash,In-store,2023-07-05
3973,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [223]:
df2.to_excel("cleaned_data.xlsx", index=False)