In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"practDatasets/earthquake1826_2026.csv")
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,id,updated,place,type,horizontalError,depthError,magError,magNst,status
0,2026-01-07 22:00:13.258000+00:00,-23.4332,-179.8984,547.033,5.5,mww,63.0,39.0,5.976,1.13,us7000rnbi,2026-01-07T22:24:28.537Z,south of the Fiji Islands,earthquake,8.66,7.704,0.093,11.0,reviewed
1,2026-01-07 04:12:56.792000+00:00,7.2863,127.0595,11.854,5.5,mww,58.0,53.0,1.485,1.40,us7000rn4a,2026-01-07T16:31:18.040Z,"53 km E of Santiago, Philippines",earthquake,5.21,4.721,0.098,10.0,reviewed
2,2026-01-07 03:02:56.040000+00:00,7.3902,126.7221,35.000,6.4,mww,118.0,30.0,1.178,1.17,us7000rn2z,2026-01-07T15:50:12.915Z,"16 km ESE of Baculin, Philippines",earthquake,7.94,1.842,0.047,44.0,reviewed
3,2026-01-06 23:10:38.371000+00:00,-17.6276,168.2465,62.384,5.0,mww,47.0,79.0,2.388,0.54,us7000rn1j,2026-01-07T12:59:00.885Z,"13 km NNW of Port-Vila, Vanuatu",earthquake,9.64,6.266,0.103,9.0,reviewed
4,2026-01-06 19:17:09.696000+00:00,37.2523,74.6137,10.000,5.2,mb,112.0,54.0,1.991,0.88,us7000rmzt,2026-01-07T05:04:55.711Z,"103 km N of Barishal, Pakistan",earthquake,6.54,1.848,0.049,136.0,reviewed

In [3]:
df.head(10)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,id,updated,place,type,horizontalError,depthError,magError,magNst,status
0,2026-01-07 22:00:13.258000+00:00,-23.4332,-179.8984,547.033,5.5,mww,63.0,39.0,5.976,1.13,us7000rnbi,2026-01-07T22:24:28.537Z,south of the Fiji Islands,earthquake,8.66,7.704,0.093,11.0,reviewed
1,2026-01-07 04:12:56.792000+00:00,7.2863,127.0595,11.854,5.5,mww,58.0,53.0,1.485,1.40,us7000rn4a,2026-01-07T16:31:18.040Z,"53 km E of Santiago, Philippines",earthquake,5.21,4.721,0.098,10.0,reviewed
2,2026-01-07 03:02:56.040000+00:00,7.3902,126.7221,35.000,6.4,mww,118.0,30.0,1.178,1.17,us7000rn2z,2026-01-07T15:50:12.915Z,"16 km ESE of Baculin, Philippines",earthquake,7.94,1.842,0.047,44.0,reviewed
3,2026-01-06 23:10:38.371000+00:00,-17.6276,168.2465,62.384,5.0,mww,47.0,79.0,2.388,0.54,us7000rn1j,2026-01-07T12:59:00.885Z,"13 km NNW of Port-Vila, Vanuatu",earthquake,9.64,6.266,0.103,9.0,reviewed
4,2026-01-06 19:17:09.696000+00:00,37.2523,74.6137,10.000,5.2,mb,112.0,54.0,1.991,0.88,us7000rmzt,2026-01-07T05:04:55.711Z,"103 km N of Barishal, Pakistan",earthquake,6.54,1.848,0.049,136.0,reviewed
5,2026-01-06 18:18:47.951000+00:00,51.8612,159.8596,41.976,5.2,mww,71.0,94.0,1.380,1.02,us7000rmzf,2026-01-06T18:39:02.040Z,"154 km SE of Vilyuchinsk, Russia",earthquake,9.35,6.526,0.110,8.0,reviewed
6,2026-01-06 10:09:26.363000+00:00,-19.2401,63.9710,10.000,5.4,mb,64.0,30.0,0.764,0.98,us7000rmuk,2026-01-07T10:33:00.539Z,"76 km NE of Port Mathurin, Mauritius",earthquake,7.36,1.838,0.063,86.0,reviewed
7,2026-01-06 07:01:19.507000+00:00,11.8498,143.8056,10.000,5.2,mb,60.0,71.0,3.879,0.52,us7000rms9,2026-01-07T07:11:23.965Z,"182 km SSW of Merizo Village, Guam",earthquake,6.82,1.874,0.043,178.0,reviewed
8,2026-01-06 06:52:57.077000+00:00,-32.6430,-177.5153,10.000,5.1,mb,29.0,126.0,5.984,0.78,us7000rms5,2026-01-06T07:11:24.040Z,south of the Kermadec Islands,earthquake,11.69,1.927,0.114,25.0,reviewed
9,2026-01-06 03:14:35.170000+00:00,17.5674,145.7890,223.590,5.0,mb,74.0,102.0,2.313,0.74,us7000rmre,2026-01-07T03:24:39.285Z,"260 km N of Saipan, Northern Mariana Islands",earthquake,11.19,7.316,0.055,106.0,reviewed

In [4]:
df.tail(10)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,id,updated,place,type,horizontalError,depthError,magError,magNst,status
106067,1841-03-11 23:15:00+00:00,19.50,-155.90,NaN,6.1,mint,NaN,NaN,NaN,NaN,official18410311231500000,2025-01-22T01:42:17.786Z,"Kona District, Hawaii",earthquake,NaN,NaN,NaN,NaN,reviewed
106068,1840-02-02 00:00:00+00:00,19.25,-155.00,NaN,6.1,mint,NaN,NaN,NaN,NaN,ushis50,2025-01-14T01:33:36.139Z,"Island of Hawai`i, Hawaii",earthquake,NaN,NaN,NaN,NaN,reviewed
106069,1840-01-18 00:00:00+00:00,36.85,-121.50,NaN,6.5,mw,NaN,NaN,NaN,NaN,cdmg18400118000000000,2021-03-04T01:39:35.713Z,"Near San Juan Bautista, California",earthquake,NaN,NaN,NaN,NaN,reviewed
106070,1838-12-12 23:30:00+00:00,19.35,-155.02,NaN,6.1,mint,NaN,NaN,NaN,NaN,official18381212233000000,2025-01-15T01:00:29.544Z,"Kilauea South Flank, Hawaii",earthquake,NaN,NaN,NaN,NaN,reviewed
106071,1838-06-25 20:00:00+00:00,37.30,-122.15,NaN,7.4,mw,NaN,NaN,NaN,NaN,official18380625200000000,2024-02-07T01:30:23.178Z,"The 1838 San Andreas Fault, California Earthquake",earthquake,NaN,NaN,NaN,NaN,reviewed
106072,1836-06-10 15:30:00+00:00,36.90,-121.50,NaN,6.4,mw,NaN,NaN,NaN,NaN,cdmg18360610153000000,2021-07-06T15:28:25.681Z,"Near San Juan Bautista, California",earthquake,NaN,NaN,NaN,NaN,reviewed
106073,1834-02-20 04:30:00+00:00,19.25,-155.00,NaN,5.9,mint,NaN,NaN,NaN,NaN,ushis43,2021-08-08T00:05:03.159Z,"Island of Hawai`i, Hawaii",earthquake,NaN,NaN,NaN,NaN,reviewed
106074,1832-01-11 04:30:00+00:00,19.35,-155.02,NaN,6.2,mint,NaN,NaN,NaN,NaN,official18320111043000000,2025-01-22T01:05:55.041Z,"Kilauea South Flank, Hawaii",earthquake,NaN,NaN,NaN,NaN,reviewed
106075,1830-01-01 00:00:00+00:00,35.35,-120.65,NaN,6.0,mw,NaN,NaN,NaN,NaN,cdmg18300101000000000,2023-08-21T06:48:28.643Z,"Near San Luis Obispo, California",earthquake,NaN,NaN,NaN,NaN,reviewed
106076,1827-09-24 04:00:00+00:00,34.00,-119.00,NaN,6.0,mw,NaN,NaN,NaN,NaN,cdmg18270924040000000,2021-02-21T09:50:44.091Z,"Channel Islands region, California",earthquake,NaN,NaN,NaN,NaN,reviewed

In [5]:
df.shape

(106077, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106077 entries, 0 to 106076
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   time             106077 non-null  object
 1   latitude         106077 non-null  float64
 2   longitude        106077 non-null  float64
 3   depth            105484 non-null  float64
 4   mag              106077 non-null  float64
 5   magType          106077 non-null  object
 6   nst              31347 non-null   float64
 7   gap              41986 non-null   float64
 8   dmin             21402 non-null   float64
 9   rms              74560 non-null   float64
 10  id               106077 non-null  object
 11  updated          106077 non-null  object
 12  place            105855 non-null  object
 13  type             106077 non-null  object
 14  horizontalError  19983 non-null   float64
 15  depthError       54440 non-null   float64
 16  magError         36554 non-null   float64
 17  magNst           42353 non-null   float64
 18  status           106077 non-null  object
dtypes: float64(12), object(7)
memory usage: 15.4+ MB

In [7]:
new_data= {"Column_Name":[],"Number_of_missing_values":[],"Percentage":[]}
df2 = pd.DataFrame(new_data)

In [8]:
df2["Column_Name"]=list(df.columns)

In [9]:
df2=df2.set_index("Column_Name")

In [10]:

for x in list(df.columns):
    df2.loc[x,"Number_of_missing_values"]=106077-df[x].count()

In [11]:
# df2=df2.reset_index()
for x in list(df2.index):
    df2.loc[x,"Percentage"]=df2.loc[x,"Number_of_missing_values"]/106077*100

In [12]:
df2

                 Number_of_missing_values  Percentage
Column_Name
time                                  0.0    0.000000
latitude                              0.0    0.000000
longitude                             0.0    0.000000
depth                               593.0    0.559028
mag                                   0.0    0.000000
magType                               0.0    0.000000
nst                               74730.0   70.448825
gap                               64091.0   60.419318
dmin                              84675.0   79.824090
rms                               31517.0   29.711436
id                                    0.0    0.000000
updated                               0.0    0.000000
place                               222.0    0.209282
type                                  0.0    0.000000
horizontalError                   86094.0   81.161798
depthError                        51637.0   48.678790
magError                          69523.0   65.540127
magNst                            63724.0   60.073343
status                                0.0    0.000000

In [13]:
df2 = df2.sort_values("Percentage",ascending=False)

In [14]:
for x in df2.index:
    if df2.loc[x,"Percentage"] > 60:
        df.drop(columns = x,inplace =True)

In [15]:
df.head(10)

,time,latitude,longitude,depth,mag,magType,rms,id,updated,place,type,depthError,status
0,2026-01-07 22:00:13.258000+00:00,-23.4332,-179.8984,547.033,5.5,mww,1.13,us7000rnbi,2026-01-07T22:24:28.537Z,south of the Fiji Islands,earthquake,7.704,reviewed
1,2026-01-07 04:12:56.792000+00:00,7.2863,127.0595,11.854,5.5,mww,1.40,us7000rn4a,2026-01-07T16:31:18.040Z,"53 km E of Santiago, Philippines",earthquake,4.721,reviewed
2,2026-01-07 03:02:56.040000+00:00,7.3902,126.7221,35.000,6.4,mww,1.17,us7000rn2z,2026-01-07T15:50:12.915Z,"16 km ESE of Baculin, Philippines",earthquake,1.842,reviewed
3,2026-01-06 23:10:38.371000+00:00,-17.6276,168.2465,62.384,5.0,mww,0.54,us7000rn1j,2026-01-07T12:59:00.885Z,"13 km NNW of Port-Vila, Vanuatu",earthquake,6.266,reviewed
4,2026-01-06 19:17:09.696000+00:00,37.2523,74.6137,10.000,5.2,mb,0.88,us7000rmzt,2026-01-07T05:04:55.711Z,"103 km N of Barishal, Pakistan",earthquake,1.848,reviewed
5,2026-01-06 18:18:47.951000+00:00,51.8612,159.8596,41.976,5.2,mww,1.02,us7000rmzf,2026-01-06T18:39:02.040Z,"154 km SE of Vilyuchinsk, Russia",earthquake,6.526,reviewed
6,2026-01-06 10:09:26.363000+00:00,-19.2401,63.9710,10.000,5.4,mb,0.98,us7000rmuk,2026-01-07T10:33:00.539Z,"76 km NE of Port Mathurin, Mauritius",earthquake,1.838,reviewed
7,2026-01-06 07:01:19.507000+00:00,11.8498,143.8056,10.000,5.2,mb,0.52,us7000rms9,2026-01-07T07:11:23.965Z,"182 km SSW of Merizo Village, Guam",earthquake,1.874,reviewed
8,2026-01-06 06:52:57.077000+00:00,-32.6430,-177.5153,10.000,5.1,mb,0.78,us7000rms5,2026-01-06T07:11:24.040Z,south of the Kermadec Islands,earthquake,1.927,reviewed
9,2026-01-06 03:14:35.170000+00:00,17.5674,145.7890,223.590,5.0,mb,0.74,us7000rmre,2026-01-07T03:24:39.285Z,"260 km N of Saipan, Northern Mariana Islands",earthquake,7.316,reviewed