In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"practDatasets/dirty_cafe_sales.csv")

In [3]:
df = df.drop_duplicates()

In [4]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [5]:
# df["Transaction ID"].str.contains("TXN").count() 
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [6]:
df.dropna(subset=["Item","Payment Method","Location"],inplace =True)

In [7]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03

In [8]:
for x in df.index:
    str(df.loc[x,"Item"])

In [18]:

        
df = df[df["Item"] != "UNKNOWN"]

In [19]:
df[df["Item"] == "UNKNOWN"].count()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [21]:
# df.reset_index(inplace =True)
df.drop(columns = "index",inplace =True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
4661,TXN_3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
4662,TXN_2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
4663,TXN_3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
4664,TXN_2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
4665,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
# df.dropna(inplace =True)
# for x in df.index:
#     str(df.loc[x,"Quantity"])

# df = df[df["Quantity"]!="UNKNOWN"]  

# df = df[df["Quantity"]!="ERROR"]  


# for x in df.index:
#     print(df.loc[x,"Quantity"])

df = df[df["Quantity"] != 0]

In [13]:
#

In [37]:
# for x in df.index:
#      df.loc[x,"Item"] = df.loc[x,"Item"][0].upper() + df.loc[x,"Item"][1:].lower()

In [41]:
# for x in df.index:
#     print(df.loc[x,"Quantity"])

2
4
4
2
2
4
5
2
2
3
2
5
4
4
3
5
5
4
4
2
1
2
4
5
5
4
1
5
2
2
2
1
4
2
3
5
1
2
3
3
5
4
4
4
2
4
3
5
2
2
5
4
4
2
2
4
5
5
5
3
5
4
2
3
5
1
1
3
3
4
3
3
5
3
2
3
5
4
4
3
2
2
3
1
1
3
4
1
4
3
1
1
5
1
1
4
4
1
1
2
3
3
2
2
3
4
1
2
5
2
5
1
5
1
4
4
5
5
5
1
4
5
1
3
3
1
3
2
3
3
3
4
3
4
5
5
3
2
3
1
3
5
2
5
2
3
5
3
4
3
4
4
2
3
4
2
3
1
2
1
1
5
5
3
5
1
5
4
1
4
1
5
3
4
1
4
2
4
3
1
4
5
1
3
2
5
5
2
4
2
3
5
1
1
5
4
3
4
4
2
4
1
4
4
4
1
1
4
5
5
1
4
3
4
1
4
3
2
2
1
3
2
3
3
3
3
2
4
1
5
4
3
1
3
5
5
4
5
4
3
3
5
5
1
5
3
5
2
5
1
1
1
1
1
4
2
3
3
5
5
4
2
5
2
5
5
1
2
4
1
4
1
5
3
5
2
1
3
1
3
5
1
2
5
3
5
2
4
1
1
3
4
3
1
4
5
3
5
5
1
1
2
2
3
5
4
4
4
3
1
3
2
3
3
4
1
1
5
1
4
5
5
3
3
2
3
5
1
5
1
4
3
2
3
4
5
1
3
3
5
3
4
4
4
5
4
2
1
1
3
3
3
3
4
2
3
4
1
3
3
5
3
4
4
4
3
1
3
2
1
4
4
4
4
3
3
1
4
3
2
1
5
2
3
5
5
3
5
5
2
5
2
3
3
1
1
2
5
1
5
2
1
1
3
4
1
2
2
2
5
5
5
5
1
2
5
1
1
1
4
5
5
2
4
1
4
2
3
2
5
4
1
1
3
4
1
1
4
2
2
3
2
4
3
2
2
1
3
1
3
2
3
1
5
4
5
1
5
3
2
2
1
2
2
2
1
5
3
5
1
1
2
4
5
4
5
2
3
2
2
5
4
2
3
3
3
5
3
3
5
2
1
5
2
1
2
1
2
4
5
1
2
1
1
2
5
2
4
5
2
2
5
5
4
4
4
5
4
4
2
3
2
1
5
5
4
2
2
4
1
4
5
2
2
2
4
3
1
2
5
4
5
1
4
1
5
1
3
1
2
1
1
2
2
4
5
4
1
3
4
1
2
5
3
2
4
3
5
5
1
3
4
2
1
2
2
3
5
4
5
5
5
3
3
3
3
1
4
4
1
3
3
3
2
5
1
2
5
2
5
1
1
2
5
4
1
4
2
4
1
2
5
4
4
1
3
5
2
2
4
5
3
3
5
1
4
5
2
2
4
4
4
5
1
4
4
5
5
2
2
2
1
1
1
2
5
5
5
5
4
4
1
1
4
5
1
1
3
2
1
4
5
2
1
4
4
3
5
4
1
2
4
2
2
1
3
2
1
3
3
1
3
5
2
2
1
4
3
1
3
5
4
3
2
2
2
5
4
4
3
5
4
2
2
4
2
1
2
5
5
5
2
2
5
4
5
5
1
1
1
3
1
5
2
1
2
3
2
5
4
5
5
5
4
2
1
4
5
2
2
5
5
5
2
5
1
5
1
1
2
5
1
1
1
5
1
2
1
2
5
2
4
1
1
5
5
1
4
2
5
5
3
5
1
3
1
5
5
5
2
2
5
5
3
5
4
5
3
2
1
2
5
2
2
2
2
1
5
4
5
5
3
1
5
4
1
2
3
5
3
5
5
3
2
5
5
4
4
3
2
4
4
3
5
5
4
5
5
1
5
3
4
3
5
2
2
1
5
3
1
1
5
5
5
3
1
2
3
2
3
3
3
4
2
2
3
1
5
2
5
1
2
3
5
4
1
2
3
5
1
3
3
3
5
4
3
4
4
2
5
3
1
1
4
4
2
4
3
4
3
1
2
1
5
5
1
3
3
3
3
4
3
3
3
1
3
4
4
1
3
2
2
4
1
4
1
5
4
3
5
1
4
2
1
1
2
2
1
1
4
2
2
3
3
5
3
5
3
2
2
2
2
3
2
2
5
3
1
3
4
4
5
3
5
3
2
5
1
5
4
3
4
4
1
2
4
4
5
5
5
3
2
2
3
3
3
2
5
3
1
5
5
3
5
4
2
2
1
2
3
5
3
3
2
4
4
1
4
3
5
3
1
5
2
4
2
1
2
4
1
3
4
4
2
1
3
1
5
1
2
5
1
3
5
5
4
5
2
2
3
5
1
3
1
1
5
2
2
5
3
4
5
5
4
1
3
1
4
4
1
4
4
5
3
1
5
1
5
2
5
4
5
3
1
5
4
4
1
4
1
4
5
4
2
1
3
4
1
4
1
4
5
3
2
2
1
3
2
5
4
5
5
5
2
4
4
4
5
2
4
3
4
4
2
5
3
2
2
1
2
4
2
5
5
4
2
3
4
4
1
2
4
4
3
5
2
5
5
3
1
4
1
5
2
5
3
3
5
5
4
4
3
2
1
2
5
1
2
5
2
1
2
1
4
1
1
1
5
2
1
1
1
4
1
2
3
5
2
3
4
1
4
5
3
3
5
4
4
1
2
1
3
2
2
1
3
5
3
5
2
1
5
5
4
2
5
3
2
1
5
1
5
2
3
5
3
4
5
3
3
2
3
2
5
5
2
4
3
2
5
2
3
1
3
1
1
2
1
4
5
5
3
3
5
2
4
4
3
3
4
2
5
3
3
1
5
4
5
4
4
3
1
1
2
5
4
2
2
5
3
2
2
5
4
4
5
1
4
5
2
3
3
4
4
1
2
5
4
1
5
1
3
3
5
5
4
5
3
1
4
5
2
2
3
1
4
3
5
3
3
3
2
1
2
3
1
2
5
5
5
1
5
2
5
2
3
4
2
1
2
1
2
2
2
4
2
4
4
1
1
5
2
3
3
3
4
3
2
3
5
4
4
5
1
1
5
5
3
3
3
1
2
3
1
4
4
5
2
3
3
3
4
5
4
5
1
2
3
2
1
2
3
1
4
5
5
2
4
3
3
3
2
5
5
2
2
5
1
3
1
2
2
5
4
3
5
2
3
3
4
4
1
5
5
3
4
5
2
1
4
1
4
5
5
4
3
1
5
5
2
4
3
5
4
4
3
1
5
3
3
5
4
5
1
3
1
2
5
2
5
1
5
4
2
3
5
1
4
3
4
1
4
3
1
3
3
3
3
1
3
5
1
4
5
4
2
1
4
1
1
2
2
2
4
3
1
1
1
4
2
4
2
5
3
2
4
1
3
5
4
1
3
5
4
3
5
5
3
1
1
5
3
5
1
5
1
2
1
5
5
5
3
5
5
5
5
4
5
2
4
4
4
1
3
1
4
1
5
2
3
1
5
4
1
4
2
2
1
5
2
4
3
3
2
3
5
2
1
4
2
5
4
4
3
1
4
4
1
4
2
1
5
2
3
2
2
3
5
5
5
3
4
4
2
5
2
3
2
3
4
2
1
4
4
3
4
2
5
2
2
3
1
4
2
1
4
1
2
1
1
5
4
4
4
3
3
3
3
1
2
5
3
3
2
1
1
4
1
5
3
2
4
4
2
3
5
4
3
5
5
3
2
2
5
4
4
1
4
2
1
3
2
2
1
2
4
1
5
2
5
3
5
4
1
2
4
5
1
5
2
3
4
2
4
1
1
1
3
1
3
5
4
5
4
4
1
3
4
4
3
5
4
4
2
1
3
3
1
5
2
2
2
3
5
2
4
4
5
5
3
5
1
4
3
5
4
1
1
2
2
2
4
4
4
5
5
3
3
4
4
3
1
5
1
4
2
5
1
5
1
4
3
2
2
5
5
5
1
3
1
1
2
2
5
2
4
5
2
5
2
5
4
1
3
2
1
5
4
3
1
2
2
1
4
1
4
1
4
2
1
4
5
3
1
4
1
4
3
5
5
2
1
2
3
5
4
5
2
3
5
1
2
3
1
4
2
4
5
2
4
2
2
4
1
3
5
5
2
3
3
2
1
3
3
1
2
1
4
5
3
5
4
1
3
5
2
5
4
1
4
1
1
1
2
4
1
2
3
5
3
1
1
4
3
1
5
4
1
1
2
2
1
3
5
3
4
1
4
2
1
4
3
1
5
5
4
3
3
2
5
3
5
1
3
2
2
5
2
5
3
3
3
5
1
3
3
3
5
2
3
4
1
3
1
4
4
5
1
4
5
5
4
5
1
2
5
4
2
3
5
2
4
2
5
3
4
1
5
3
4
1
4
2
3
1
2
1
4
2
2
5
5
2
5
2
3
3
3
1
3
4
1
2
4
2
2
4
3
1
4
5
3
5
2
1
2
1
2
2
3
2
4
4
4
1
2
3
1
2
1
5
3
4
3
5
3
2
5
5
5
3
5
5
3
3
4
1
2
2
2
3
3
5
3
5
2
2
5
1
3
5
5
5
3
3
3
2
4
5
2
1
4
4
5
3
2
4
4
2
2
3
3
3
4
2
5
3
3
5
4
1
5
1
4
1
1
4
4
5
3
2
3
4
4
1
3
2
3
3
4
1
1
1
2
4
1
2
1
1
5
5
1
1
1
4
1
1
1
1
4
2
1
2
3
5
3
5
2
5
3
2
3
4
1
4
3
5
3
4
4
5
3
1
3
1
5
1
3
1
2
3
4
4
2
1
3
3
1
4
2
2
5
3
5
5
4
3
1
5
4
3
2
1
3
2
1
3
3
4
5
5
1
3
1
5
4
4
4
2
1
2
2
4
3
1
5
1
5
4
1
2
5
4
2
1
4
3
2
1
2
5
3
1
4
2
2
3
2
4
5
4
1
4
2
1
5
1
4
2
2
2
4
4
3
5
5
5
5
2
5
1
5
2
3
3
3
4
2
3
1
5
4
1
5
5
3
1
3
2
1
3
3
2
4
3
4
4
2
1
5
3
3
2
3
1
4
2
1
4
2
5
1
1
5
4
3
1
4
2
1
1
3
2
3
3
3
5
2
4
5
3
5
2
5
2
3
5
5
4
5
5
2
3
5
3
2
3
5
3
4
3
4
1
5
5
2
3
2
2
4
4
4
1
5
5
1
4
5
2
2
4
1
4
2
4
1
5
3
1
4
4
5
4
4
5
5
3
3
5
3
2
1
5
3
1
2
4
4
5
3
3
1
1
5
4
1
3
5
3
5
3
5
3
2
5
5
4
2
2
2
5
2
3
5
2
3
5
3
3
2
1
1
2
5
5
2
3
3
1
3
2
2
2
4
1
4
5
4
5
5
3
2
5
1
1
3
4
4
5
2
1
3
5
4
5
3
2
3
4
1
5
1
4
5
2
1
3
5
2
5
5
4
3
1
2
5
4
5
1
4
3
2
3
1
5
3
3
3
3
2
3
4
3
2
3
4
4
4
1
1
4
4
2
4
2
2
5
2
5
3
4
1
4
4
3
5
5
5
1
5
3
1
3
4
2
1
5
1
2
3
4
5
3
3
5
1
4
3
4
5
3
3
2
2
4
2
3
2
2
5
2
3
2
5
1
3
4
3
5
2
4
5
5
2
3
4
1
3
5
2
1
5
1
2
5
3
4
5
5
2
5
5
5
5
3
2
5
5
3
1
4
2
5
1
3
5
3
4
1
2
1
3
5
2
3
2
3
1
4
3
4
5
3
5
5
1
2
2
1
2
3
3
1
4
2
3
1
3
2
4
1
3
4
5
4
4
4
5
2
1
3
3
5
1
4
1
4
1
4
2
4
5
2
1
2
5
2
3
5
3
1
1
1
1
2
2
3
2
2
5
5
3
1
4
3
3
5
5
2
4
2
5
4
4
5
1
1
4
4
1
5
2
4
1
4
2
5
5
1
3
5
5
2
4
3
5
3
5
1
2
2
4
2
3
1
5
4
2
1
3
1
1
1
2
2
2
4
4
1
4
2
5
2
4
3
4
3
5
2
5
2
3
1
4
4
5
5
2
4
4
3
4
3
1
2
4
3
3
3
5
4
5
4
5
3
1
2
5
4
1
2
5
4
2
2
2
4
1
4
3
1
3
3
4
4
2
4
1
5
5
3
1
2
3
5
4
3
1
1
4
5
4
3
1
2
1
3
4
5
1
5
3
5
3
4
5
1
1
1
4
3
5
3
3
5
3
4
4
2
5
1
3
1
4
5
1
5
2
4
5
4
4
1
5
4
2
5
4
1
3
5
4
1
2
1
3
3
2
1
4
2
3
2
3
4
3
3
3
1
3
2
2
1
4
5
2
1
3
2
1
5
2
4
2
2
2
1
3
2
1
1
1
1
2
3
2
4
3
1
4
5
1
5
2
1
1
3
5
4
1
2
1
1
3
2
2
5
4
4
5
1
4
3
1
5
5
3
5
4
4
5
2
2
4
5
4
4
1
4
1
3
1
2
1
1
1
5
3
3
1
2
3
2
2
4
1
1
5
4
5
2
4
1
1
3
4
4
1
5
5
5
2
4
3
2
3
2
3
4
5
2
2
3
3
2
2
3
3
2
1
2
2
4
3
1
3
4
2
1
5
4
2
4
2
4
5
1
1
2
1
1
3
3
4
3
4
3
1
5
1
4
3
4
2
5
2
3
4
5
2
3
3
3
2
4
1
1
4
5
3
1
2
4
4
2
2
2
1
5
2
5
3
2
5
4
5
4
2
1
2
2
5
4
1
3
4
5
1
3
2
2
1
1
5
2
2
1
1
3
4
2
4
2
4
3
1
1
1
3
4
2
5
2
1
2
5
3
3
2
1
2
3
3
4
4
2
4
2
5
5
3
5
3
2
5
1
4
1
4
4
5
3
4
1
3
3
5
4
5
2
5
5
2
1
4
1
3
5
1
5
3
2
4
5
3
3
1
3
5
5
4
4
4
2
2
3
2
4
2
2
1
2
5
4
1
1
3
4
4
4
4
3
5
4
2
5
4
5
5
2
4
5
3
4
3
1
2
4
4
3
2
1
5
4
3
5
2
1
2
1
5
1
1
5
4
5
1
1
3
3
5
2
5
5
3
5
1
3
1
1
3
5
2
5
1
1
4
4
3
4
2
3
4
3
3
1
3
3
5
5
1
2
1
3
4
3
4
5
3
1
4
4
1
3
4
2
4
2
1
5
2
4
4
4
2
5
2
2
1
3
2
2
4
1
5
2
2
2
5
4
3
5
5
2
2
5
2
5
2
2
1
2
5
4
1
3
4
3
4
5
3
2
1
1
5
5
1
5
2
1
3
4
2
5
3
2
2
5
3
1
4
2
4
2
2
2
2
4
5
5
4
3
5
1
5
1
3
2
3
5
5
1
2
3
2
2
1
3
4
4
2
1
5
4
2
4
5
2
5
5
1
4
2
2
5
4
4
5
1
5
4
4
3
5
5
3
4
2
4
3
5
5
2
4
5
4
4
1
5
2
3
2
1
1
1
1
2
1
5
3
1
1
5
2
4
4
2
5
2
4
5
2
5
3
3
2
5
2
4
2
2
5
3
4
3
4
4
5
3
2
5
2
1
5
3
4
5
3
4
1
1
4
2
4
3
2
2
3
1
2
3
4
5
1
2
4
2
2
3
5
4
3
1
5
4
3
1
4
5
5
3
4
2
5
3
4
2
1
2
3
4
5
4
5
1
1
4
1
4
5
1
5
1
1
2
3
1
5
2
3
5
1
5
5
4
2
2
4
4
3
3
3
3
5
4
1
2
5
1
4
3
2
3
1
3
2
1
3
4
3
3
4
5
3
2
3
3
4
4
5
2
5
5
2
5
2
2
1
5
1
2
5
1
1
1
1
3
2
2
5
5
2
4
2
4
4
3
2
4
5
4
3
1
2
4
2
2
2
5
5
3
5
4
2
1
2
2
2
4
4
2
1
3
1
3
4
3
1
1
1
1
5
4
2
1
5
1
2
4
5
5
4
5
4
3
1
1
5
3
4
2
2
4
1
3
1
3
3
5
1
2
3
2
1
2
3
3
5
1
2
4
1
1
5
5
3
4
5
1
4
4
3
5
4
3
5
4
1
4
5
1
1
3
2
2
2
5
5
3
5
3
2
4
2
4
4
1
3
1
1
1
2
2
2
2
2
2
5
3
1
4
4
2
2
2
5
1
1
3
1
2
2
1
5
4
4
3
1
4
5
4
2
2
3
1
2
3
1
5
5
1
2
2
1
5
1
4
3
3
2
2
1
2
4
3
5
4
5
2
3
1
5
2
1
3
5
4
3
2
3
3
4
1
1
5
5
4
5
3
2
2
2
3
4
4
1
5
2
3
3
2
5
3
1
5
5
5
1
5
1
5
4
2
4
5
4
4
1
4
3
1
4
2
3
3
1
1
1
4
2
3
4
5
5
4
3
4
5
5
3
4
2
1
3
3
5
2
2
1
4
1
3
1
3
5
5
5
1
2
1
1
1
3
3
2
1
3
5
4
5
4
1
4
1
3
5
4
1
2
1
1
4
1
2
5
1
2
3
5
2
1
4
2
2
5
3
1
1
4
1
5
2
5
4
4
4
2
1
4
5
5
1
2
4
2
4
2
2
4
3
5
1
4
5
3
2
4
1
1
3
1
4
2
5
1
1
2
5
2
3
2
2
5
1
1
3
4
5
1
5
4
3
2
3
3
5
2
3
1
3
3
2
1
5
3
1
1
3
2
1
3
2
5
5
5
2
4
1
1
2
4
3
3
5
5
2
4
5
2
3
1
4
3
3
2
3
3
4
3
2
1
1
5
5
2
5
1
4
3
2
3
2
2
2
1
3
2
1
3
4
2
2
2
2
4
2
3
1
2
3
2
4
1
4
3
5
5
5
3
1
5
1
1
3
2
5
3
2
1
2
4
3
4
4
4
1
4
4
5
4
4
1
4
4
3
1
5
4
3
2
1
4
1
4
5
4
3
2
4
2
3
4
4
2
1
2
4
5
1
3
4
3
2
5
3
4
1
2
3
5
4
4
5
5
2
2
2
3
5
5
5
5
5
2
3
3
5
2
4
1
2
2
2
5
2
1
1
1
5
4
5
4
1
3
2
1
5
2
1
2
5
2
4
1
1
4
3
3
4
2
5
3
5
5
5
2
3
4
5
1
4
3
2
5
4
4
5
1
5
5
5
3
2
3
3
4
4
3
3
4
3
3
4
3
5
2
1
5
2
2
2
3
5
2
5
4
1
1
5
5
5
4
4
4
5
2
3
1
3
1
2
2
1
3
5
3
2
4
3
2
3
3
5
1
3
5
2
1
1
3
1
5
1
1
3
5
2
1
5
2
2
1
1
5
3
3
4
5
5
2
5
5
2
3
1
3
4
3
1
5
2
4
4
4
5
4
1
4
5
2
3
4
2
1
4
2
4
4
2
1
5
2
4
1
5
2
5
1
2
2
5
2
5
1
3
4
4
1
5
5
4
1
5
2
2
2
3
1
1
3
1
1
5
2
4
1
5
5
2
1
3
3
1
4
3
4
5
2
2
4
1
4
2
4
5
4
2
2
4
3
2
5
5
4
4
1
2
5
2
3
4
3

In [43]:
df.head(20)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
6,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
7,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
8,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
9,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
10,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
11,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
12,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
14,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
15,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
16,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
18,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
19,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
20,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
21,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09