In [1]:
import pandas as pd

In [122]:
df1 = pd.read_csv(r"uselessDatasets/employee.csv")
df2 = pd.read_csv(r"uselessDatasets/dep.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'uselessDatasets/employee.csv'

In [21]:
df1

   emp_id    name  dept_id  salary
0       1     Ali       10   60000
1       2    Sara       20   48000
2       3   Ahmed       10   72000
3       4  Ayesha       30   51000
4       5  Hassan       20   45000
5       6    Noor       30   68000

In [20]:
df2

   dept_id dept_name
0       10        IT
1       20        HR
2       30   Finance

In [30]:
temp= df1[df1["salary"] > 50000]

62750.0

In [54]:
df3 = df1.merge(df2,how = "outer")
df3

   emp_id    name  dept_id  salary dept_name
0       1     Ali       10   60000        IT
1       3   Ahmed       10   72000        IT
2       2    Sara       20   48000        HR
3       5  Hassan       20   45000        HR
4       4  Ayesha       30   51000   Finance
5       6    Noor       30   68000   Finance

In [61]:
sorted_dataframe = df3.sort_values("salary")
sorted_dataframe

   emp_id    name  dept_id  salary dept_name
3       5  Hassan       20   45000        HR
2       2    Sara       20   48000        HR
4       4  Ayesha       30   51000   Finance
0       1     Ali       10   60000        IT
5       6    Noor       30   68000   Finance
1       3   Ahmed       10   72000        IT

In [66]:
df1 = pd.read_csv(r"uselessDatasets/student.csv")
df2 = pd.read_csv(r"uselessDatasets/marks.csv")
df1

   student_id    name  class
0           1     Ali     10
1           2    Sara     10
2           3   Ahmed      9
3           4  Ayesha      9
4           5  Hassan     10

In [68]:
df2

   student_id  subject  marks
0           1     Math     78
1           1  Science     65
2           2     Math     45
3           2  Science     40
4           3     Math     88
5           3  Science     92
6           4     Math     30
7           4  Science     35
8           5     Math     55
9           5  Science     60

In [76]:
merged = df1.merge(df2, on = "student_id")
merged

   student_id    name  class  subject  marks
0           1     Ali     10     Math     78
1           1     Ali     10  Science     65
2           2    Sara     10     Math     45
3           2    Sara     10  Science     40
4           3   Ahmed      9     Math     88
5           3   Ahmed      9  Science     92
6           4  Ayesha      9     Math     30
7           4  Ayesha      9  Science     35
8           5  Hassan     10     Math     55
9           5  Hassan     10  Science     60

In [96]:
avg_marks_df = merged.groupby(["student_id","name","class"]).mean(numeric_only= True)
avg_marks_df = avg_marks_df.rename(columns= {"marks":"average_marks"})

In [102]:
avg_marks_df.insert(0,"PASS/FAIL",value=None)

ValueError: cannot insert PASS/FAIL, already exists

In [106]:
avg_marks_df = avg_marks_df.drop(columns = "PASS/FAIL")

In [108]:
avg_marks_df.insert(1,"PASS/FAIL",value=None)

In [109]:
avg_marks_df

                         average_marks PASS/FAIL
student_id name   class
1          Ali    10              71.5      None
2          Sara   10              42.5      None
3          Ahmed  9               90.0      None
4          Ayesha 9               32.5      None
5          Hassan 10              57.5      None

In [118]:
import numpy as np
avg_marks_df["PASS/FAIL"]= np.where(
        avg_marks_df["average_marks"] >= 50,"P","F"
)

In [119]:
avg_marks_df

                         average_marks PASS/FAIL
student_id name   class
1          Ali    10              71.5         P
2          Sara   10              42.5         F
3          Ahmed  9               90.0         P
4          Ayesha 9               32.5         F
5          Hassan 10              57.5         P

KeyError: 'Column not found: marks'